'use client';
import { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'ar';
type Dictionary = Record<string, string>;

const en: Dictionary = {
  brand:'FleetFlow', marketplace:'Marketplace', deals:'Deals', features:'Features', signIn:'Sign in', getStarted:'Get started',
  heroEyebrow:'The smarter way to rent and manage', heroTitle:'Every journey, perfectly managed.', heroText:'Book exceptional cars with complete flexibility—or run your entire rental fleet from one calm, connected workspace.', browseCars:'Browse cars', listFleet:'List your fleet', liveVehicles:'live vehicles', trustedCompanies:'trusted companies', completedTrips:'completed trips',
  featured:'Featured vehicles', featuredText:'Curated drives from trusted local companies.', viewAll:'View all', from:'from', day:'day', days:'days', hour:'hour', hours:'hours', week:'week', weeks:'weeks', month:'month', months:'months',
  flexibleTitle:'Built around the way you move', flexibleText:'From one hour downtown to a month on the coast, choose exactly the time you need.', smartBooking:'Smart booking', smartBookingText:'Live availability, instant pricing, and protected reservations.', trustedFleet:'Trusted fleet', trustedFleetText:'Verified companies, maintained vehicles, and transparent history.', realSavings:'Real savings', realSavingsText:'Live deals appear automatically on every eligible vehicle.',
  readyTitle:'Ready to move differently?', readyText:'Join thousands of drivers and modern mobility teams already using FleetFlow.', exploreFleet:'Explore the fleet', noHiddenFees:'No hidden fees', verifiedPartners:'Verified partners', instantBooking:'Instant booking', averageRating:'average rating', fleetflowDifference:'The FleetFlow difference', privacy:'Privacy', terms:'Terms', saveTwenty:'Save 20%', footerText:'© 2026 FleetFlow. Built for the road ahead.',
  overview:'Overview', fleet:'Fleet', rentals:'Rentals', promotions:'Promotions', premiumServices:'Premium services', browse:'Browse cars', settings:'Settings', support:'Help & support', workspace:'Workspace', administrator:'Administrator', verifiedDriver:'Verified driver', logout:'Sign out', searchAnything:'Search anything…', personal:'Personal',
  goodMorning:'Good morning', overviewText:'Here is what is moving across your business today.', grossRevenue:'Gross revenue', pendingRequests:'Pending requests', activeRentals:'Active rentals', fleetSize:'Fleet size', monthlyRevenue:'Monthly revenue', utilization:'Fleet utilization', recentRentals:'Recent rentals', viewPipeline:'View pipeline', availability:'Availability', available:'Available', maintenance:'Maintenance', retired:'Retired', exportReport:'Export report', exportCsv:'Export CSV', previousPeriod:'vs previous period', performanceSixMonths:'Performance over the last 6 months', lastSixMonths:'Last 6 months', latestRequests:'Latest requests and returns across your fleet', status:'Status', thisMonth:'this month', newRequests:'new', inService:'in service',
  myNextDrive:'Your next drive starts here', whereNext:'Where will you go next?', upcomingTrips:'Upcoming trips', totalRentals:'Total rentals', lifetimeSpend:'Lifetime spend', loyalty:'Loyalty status', goldDriver:'Gold driver', currentRental:'Current rental', recommended:'Recommended for you', premiumNoFees:'Premium vehicles, flexible terms, and no hidden fees.', manageRental:'Manage rental', topRatedNearby:'Top-rated vehicles ready nearby',
  manageFleet:'Manage vehicles, pricing, and availability in one place.', addVehicle:'Add vehicle', searchFleet:'Search make, model, or plate…', allStatuses:'All statuses', edit:'Edit', delete:'Delete', details:'Details', rentalHistory:'Rental history', per:'per', seats:'seats', automatic:'Automatic', manual:'Manual', noVehicles:'No vehicles found', noVehiclesText:'Try another filter or add a new vehicle to your fleet.', filters:'Filters', totalFleet:'Total fleet',
  vehicleDetails:'Vehicle details', basicInformation:'Basic information and specifications.', make:'Make', model:'Model', year:'Year', category:'Category', gearbox:'Gearbox', fuel:'Fuel', color:'Color', licensePlate:'License plate', odometer:'Odometer', miles:'mi', location:'Location', featuresLabel:'Features', pricing:'Flexible pricing', pricingText:'Set an independent price for every duration.', image:'Cover image', cancel:'Cancel', save:'Save changes', create:'Add vehicle', saving:'Saving…', confirmDelete:'Delete this vehicle?', deleteHint:'Vehicles with current bookings cannot be deleted.', choosePhoto:'Choose a photo for the marketplace.',
  lifetimeRevenue:'Lifetime revenue', completedTripsLabel:'Completed trips', currentBookings:'Current bookings', completeVehicleRecord:'Complete booking record for this vehicle',
  rentalPipeline:'Rental pipeline', rentalPipelineText:'Move every request from confirmation to return.', all:'All', pending:'Pending', active:'Active', completed:'Completed', cancelled:'Cancelled', confirm:'Confirm request', complete:'Complete rental', cancelRental:'Cancel rental', noRentals:'No rentals here', noRentalsText:'Bookings in this state will appear here.', customer:'Customer', vehicle:'Vehicle', dates:'Dates', duration:'Duration', total:'Total', discount:'Discount', company:'Company', reservation:'Reservation', billActions:'Bill & actions', proposal:'Proposal', bill:'Bill', adjust:'Adjust', discounts:'discounts', premiumService:'premium service', premiumServicesCount:'premium services', searchReservations:'Search reservations…',
  turnaroundTitle:'1-hour turnaround protected automatically', turnaroundText:'Every pending or active reservation blocks an additional hour for inspection, cleaning, maintenance, and fueling before the next trip.',
  adjustBill:'Adjust rental bill', premiumServiceLines:'Premium service lines', adminAdjustHint:'Company administrators can change days, daily price, and discounts.', catalogPrice:'Catalog', priceDay:'Price/day', lineDiscount:'Line discount', billSummary:'Bill summary', vehicleRental:'Vehicle rental', promotion:'Promotion', additionalBillDiscount:'Additional bill discount', updatedTotal:'Updated total', updatedPdfHint:'The updated PDF bill becomes available immediately in the renter’s account.', saveIssueBill:'Save & issue updated bill', billUpdated:'Bill updated and shared with the renter account',
  promotionTitle:'Promotions & discounts', promotionText:'Create targeted offers for your whole fleet or selected vehicles.', newPromotion:'New promotion', live:'Live', scheduled:'Scheduled', expired:'Expired', paused:'Paused', redemptions:'redemptions', wholeFleet:'Whole fleet', selectedVehicles:'Selected vehicles', pause:'Pause', enable:'Enable', promoName:'Promotion name', promoCode:'Promo code', discountType:'Discount type', percentage:'Percentage', fixed:'Fixed amount', value:'Value', starts:'Starts on', ends:'Ends on', minimum:'Minimum quantity', applies:'Applies to', launch:'Launch promotion', liveOffersGenerated:'Your live offers generated', promoBookingsUp:'Promotional bookings are up 18% compared with last month.', everyAvailableVehicle:'Every available vehicle', chooseSpecificVehicles:'Choose specific vehicles', campaignBuilder:'Campaign builder', offerInsights:'Your live offers generated $7,840 this month', offerInsightsText:'Promotional bookings are up 18% compared with last month.', entireFleetHint:'Every available vehicle', selectedHint:'Choose specific vehicles', editPromotion:'Edit promotion', createPromotion:'Create a promotion',
  servicesEyebrow:'Rental add-ons', servicesPageText:'Set the daily price and availability. Renters can select only how many days they need.', addService:'Add service', pricingControlTitle:'You control pricing and discounts', pricingControlText:'Catalog prices are copied into each proposal. Company admins can later adjust service days, daily prices, line discounts, and an additional bill discount. Renters can change days only.', pricePerServiceDay:'Price per service day', visibleRenters:'Visible to renters', servicePaused:'Paused', serviceName:'Service name', description:'Description', pricePerDay:'Price per day', serviceDescriptionPlaceholder:'Describe what the renter receives', serviceNamePlaceholder:'Airport meet & greet', addPremiumService:'Add premium service', addServiceText:'Create another daily add-on for your renters', serviceUpdated:'Service pricing updated', serviceRemoved:'Service removed', serviceAdded:'Premium service added', removeServiceConfirm:'Existing bills will keep their saved service details.',
  findDrive:'Find your perfect drive', findDriveText:'Book by the hour, day, week, or month.', searchCars:'Search cars…', priceView:'Displayed price', sortBy:'Sort by', priceLow:'Price: low to high', newest:'Newest first', rentNow:'Rent now', noCars:'No cars match your filters', noCarsText:'Try a different category, gearbox, or search.', clearFilters:'Clear filters', pickupNear:'Pick-up near', allGearboxes:'All gearboxes', off:'off', savedCar:'Save car',
  everythingNeeded:'Everything you need', protectedBooking:'Protected booking · no hidden fees', noUpcomingBookings:'No upcoming bookings', turnaroundProtectedUntil:'Turnaround protected until', useCode:'Use',
  bookTitle:'Complete your booking', pickRate:'Choose a rate type', quantity:'Quantity', pickupTime:'Pick-up time', returnTime:'Return time', promoOptional:'Promo code (optional)', apply:'Apply', promoApplied:'Promotion applied', subtotal:'Subtotal', confirmBooking:'Confirm booking', busyPeriods:'Busy periods', busyHint:'This vehicle is already reserved during these windows.', rentalDates:'Rental dates', chooseDate:'Choose date', pickup:'Pick-up', returnDate:'Return date', protectedTurnaround:'Protected vehicle turnaround', protectedTurnaroundText:'FleetFlow keeps 1 hour between every two reservations for inspection, cleaning, maintenance, and fueling.', noBusyPeriods:'No upcoming busy periods', unavailableTime:'Unavailable at the selected pick-up time', nextReady:'Next ready after the protected turnaround:', calendarDaysOpen:'calendar days open before the next reservation', mustReturnBy:'Vehicle must return by', serviceWindow:'so the company receives its 1-hour service window.', windowOpen:'Your selected window is open', noLaterReservation:'No later reservation currently limits this booking.', adjustedTurnaround:'Adjusted by 1 hour for turnaround', overlapDetected:'Reservation overlap detected', useAvailableRange:'Use available range ending', customizeTrip:'Customize your trip', renterDaysOnly:'You can adjust service days only', numberDays:'Number of days', rentalProposal:'Rental proposal', pdfAfterConfirmation:'A detailed PDF bill will be issued after confirmation', bookingSent:'Rental proposal and PDF bill issued successfully', chooseRange:'Choose a start and end date from the availability calendar.', rangeReserved:'The selected range reaches a reserved period. Choose an earlier return date.',
  calendarSelectDates:'Select rental dates', calendarReservedHint:'Reserved dates are disabled automatically', open:'Available', selected:'Selected', reserved:'Reserved', turnaround:'1-hour turnaround', rangeCrossesReservation:'That range crosses an existing reservation. Reserved dates cannot be selected.',
  historyTitle:'Complete rental history', historyText:'Track upcoming, current, and past drives in one place.',
  welcomeBack:'Welcome back', loginText:'Sign in to continue to your workspace.', email:'Email address', password:'Password', remember:'Remember me', forgot:'Forgot password?', newHere:'New to FleetFlow?', createAccount:'Create account', demoAccounts:'Try a demo account', renter:'Renter', companyRole:'Company', join:'Join FleetFlow', registerText:'Create a renter profile or company workspace.', fullName:'Full name', companyName:'Company name', haveAccount:'Already have an account?', builtJourney:'Built for every journey', driveFuture:'Drive the future of mobility.', fleetForward:'Your fleet. Your way forward.', authText:'One connected platform for exceptional rentals, flexible pricing, and effortless fleet operations.', authAvailability:'Live availability and protected bookings', authRates:'Flexible hourly to monthly rates', authTrust:'Trusted companies and transparent history', verifiedFleet:'Verified fleet', premiumCars:'17 premium cars', legalText:'By continuing, you agree to FleetFlow’s Terms and Privacy Policy.',
  invoiceBack:'Back to rentals', pdf:'PDF', emailAction:'Email', whatsapp:'WhatsApp', print:'Print', issued:'Issued', issuedBy:'Issued by', billedTo:'Billed to', rentedVehicle:'Rented vehicle', transmission:'Transmission', detailedBreakdown:'Detailed rent breakdown', descriptionColumn:'Description', amount:'Amount', totalDue:'Total due', billAdjustment:'Bill adjustment', invoiceProtection:'Protected FleetFlow rental', invoiceProtectionText:'This bill includes the vehicle, schedule, promotion, premium services, and company adjustments.', thankYou:'Thank you for choosing FleetFlow.', shareDownloaded:'PDF downloaded. Attach it in the opened conversation.', rentalInvoice:'Rental invoice', rentalProposalDoc:'Rental proposal', pickupLocation:'Pickup location', ratePlan:'Rate plan', vehicleDiscount:'Vehicle discount', serviceDiscount:'Service discount', additionalCompanyDiscount:'Additional company discount', totalDiscounts:'Total discounts', invoiceRentalSuffix:'rental', unablePreparePdf:'Unable to prepare PDF', rentalBillReady:'Your FleetFlow rental bill is ready. The PDF has been downloaded for attachment. You can also view it here:',
  loading:'Loading…', close:'Close', All:'All', to:'to', use:'Use', everythingNeed:'Everything you need', tryDifferentFilters:'Try a different category, gearbox, or search.', turnaroundUntil:'Turnaround protected until', tryAgain:'Try again', saved:'Saved', copied:'Copied', theme:'Theme', language:'Language', system:'System', light:'Light', dark:'Dark', saveAction:'Save', add:'Add', remove:'Remove', search:'Search',
  'Luxury sedan':'Luxury sedan', Executive:'Executive', 'Premium SUV':'Premium SUV', 'Electric SUV':'Electric SUV', Sedan:'Sedan', Performance:'Performance', SUV:'SUV', 'Luxury SUV':'Luxury SUV', 'Electric sedan':'Electric sedan',
  Automatic:'Automatic', Manual:'Manual', Hybrid:'Hybrid', Electric:'Electric', Petrol:'Petrol', Diesel:'Diesel',
  'GPS':'GPS', 'Heated seats':'Heated seats', 'Apple CarPlay':'Apple CarPlay', 'Premium audio':'Premium audio', '360° camera':'360° camera', 'Virtual cockpit':'Virtual cockpit', 'Adaptive cruise':'Adaptive cruise', CarPlay:'CarPlay', 'Lane assist':'Lane assist', 'Keyless entry':'Keyless entry', 'Pilot assist':'Pilot assist', 'Panoramic roof':'Panoramic roof', '7 seats':'7 seats', 'Blind spot assist':'Blind spot assist', 'Massage seats':'Massage seats', 'Meridian audio':'Meridian audio', 'Chauffeur package':'Chauffeur package', 'Burmester audio':'Burmester audio', 'Sky lounge':'Sky lounge', 'Parking assist':'Parking assist', 'Sport chrono':'Sport chrono', 'BOSE audio':'BOSE audio', 'Adaptive suspension':'Adaptive suspension', 'Matrix LED':'Matrix LED', 'Bang & Olufsen':'Bang & Olufsen', 'Air suspension':'Air suspension', Autopilot:'Autopilot', 'Supercharger access':'Supercharger access', 'Glass roof':'Glass roof', 'Premium connectivity':'Premium connectivity', 'Google built-in':'Google built-in', 'Pilot pack':'Pilot pack', 'Harman Kardon':'Harman Kardon', 'Vehicle-to-load':'Vehicle-to-load', 'Highway assist':'Highway assist', 'Ultra-fast charging':'Ultra-fast charging', 'Relaxation seats':'Relaxation seats', 'Driving assistant':'Driving assistant',
  'Professional driver':'Professional driver', 'Executive chauffeur':'Executive chauffeur', 'EV-trained driver':'EV-trained driver', 'Loading & offloading help':'Loading & offloading help', 'Luggage concierge':'Luggage concierge', 'Child safety seat':'Child safety seat', 'Premium child seat':'Premium child seat', 'In-car Wi-Fi':'In-car Wi-Fi', 'Executive Wi-Fi':'Executive Wi-Fi', 'Connected car Wi-Fi':'Connected car Wi-Fi', driverDescription:'Licensed private driver for local or long-distance travel.', luggageDescription:'A trained assistant to load and offload luggage safely.', childSeatDescription:'Clean, inspected child seat installed before pickup.', wifiDescription:'Unlimited high-speed mobile Wi-Fi for the whole trip.',
};

const ar: Dictionary = {
  brand:'فليت فلو', marketplace:'سوق السيارات', deals:'العروض', features:'المميزات', signIn:'تسجيل الدخول', getStarted:'ابدأ الآن',
  heroEyebrow:'الطريقة الأذكى للتأجير والإدارة', heroTitle:'كل رحلة، بإدارة مثالية.', heroText:'احجز سيارات استثنائية بمرونة كاملة — أو أدر أسطول التأجير بالكامل من مساحة عمل هادئة ومتكاملة.', browseCars:'تصفح السيارات', listFleet:'أضف أسطولك', liveVehicles:'سيارة متاحة', trustedCompanies:'شركة موثوقة', completedTrips:'رحلة مكتملة',
  featured:'سيارات مميزة', featuredText:'سيارات مختارة من شركات محلية موثوقة.', viewAll:'عرض الكل', from:'ابتداءً من', day:'يوم', days:'أيام', hour:'ساعة', hours:'ساعات', week:'أسبوع', weeks:'أسابيع', month:'شهر', months:'أشهر',
  flexibleTitle:'مصمم ليناسب طريقة تنقلك', flexibleText:'من ساعة واحدة في المدينة إلى شهر على الساحل، اختر المدة التي تحتاجها بالضبط.', smartBooking:'حجز ذكي', smartBookingText:'توفر مباشر وأسعار فورية وحجوزات محمية.', trustedFleet:'أسطول موثوق', trustedFleetText:'شركات موثقة وسيارات مصانة وسجل شفاف.', realSavings:'توفير حقيقي', realSavingsText:'تظهر العروض المباشرة تلقائياً على كل سيارة مؤهلة.',
  readyTitle:'جاهز لتتحرك بطريقة مختلفة؟', readyText:'انضم إلى آلاف السائقين وشركات التنقل الحديثة التي تستخدم فليت فلو.', exploreFleet:'استكشف الأسطول', noHiddenFees:'بدون رسوم خفية', verifiedPartners:'شركاء موثّقون', instantBooking:'حجز فوري', averageRating:'متوسط التقييم', fleetflowDifference:'الفرق مع فليت فلو', privacy:'الخصوصية', terms:'الشروط', saveTwenty:'وفّر 20٪', footerText:'© 2026 فليت فلو. صُمم للطريق أمامك.',
  overview:'نظرة عامة', fleet:'الأسطول', rentals:'الإيجارات', promotions:'العروض', premiumServices:'الخدمات المميزة', browse:'تصفح السيارات', settings:'الإعدادات', support:'المساعدة والدعم', workspace:'مساحة العمل', administrator:'مدير النظام', verifiedDriver:'سائق موثق', logout:'تسجيل الخروج', searchAnything:'ابحث عن أي شيء…', personal:'شخصي',
  goodMorning:'صباح الخير', overviewText:'إليك حركة أعمالك اليوم.', grossRevenue:'إجمالي الإيرادات', pendingRequests:'طلبات معلقة', activeRentals:'إيجارات نشطة', fleetSize:'حجم الأسطول', monthlyRevenue:'الإيرادات الشهرية', utilization:'استخدام الأسطول', recentRentals:'أحدث الإيجارات', viewPipeline:'عرض المسار', availability:'حالة التوفر', available:'متاحة', maintenance:'قيد الصيانة', retired:'متقاعدة', exportReport:'تصدير التقرير', exportCsv:'تصدير CSV', previousPeriod:'مقارنة بالفترة السابقة', performanceSixMonths:'الأداء خلال آخر 6 أشهر', lastSixMonths:'آخر 6 أشهر', latestRequests:'أحدث الطلبات وعمليات الإرجاع في أسطولك', status:'الحالة', thisMonth:'هذا الشهر', newRequests:'جديد', inService:'قيد الخدمة',
  myNextDrive:'رحلتك القادمة تبدأ هنا', whereNext:'إلى أين ستكون رحلتك القادمة؟', upcomingTrips:'رحلات قادمة', totalRentals:'إجمالي الإيجارات', lifetimeSpend:'إجمالي الإنفاق', loyalty:'حالة الولاء', goldDriver:'سائق ذهبي', currentRental:'الإيجار الحالي', recommended:'مقترحة لك', premiumNoFees:'سيارات مميزة وشروط مرنة وبدون رسوم خفية.', manageRental:'إدارة الإيجار', topRatedNearby:'سيارات عالية التقييم متاحة بالقرب منك',
  manageFleet:'أدر السيارات والأسعار والتوفر من مكان واحد.', addVehicle:'إضافة سيارة', searchFleet:'ابحث بالماركة أو الموديل أو اللوحة…', allStatuses:'كل الحالات', edit:'تعديل', delete:'حذف', details:'التفاصيل', rentalHistory:'سجل الإيجار', per:'لكل', seats:'مقاعد', automatic:'أوتوماتيك', manual:'يدوي', noVehicles:'لا توجد سيارات', noVehiclesText:'جرّب مرشحاً آخر أو أضف سيارة جديدة إلى أسطولك.', filters:'المرشحات', totalFleet:'إجمالي الأسطول',
  vehicleDetails:'تفاصيل السيارة', basicInformation:'المعلومات الأساسية والمواصفات.', make:'الماركة', model:'الموديل', year:'السنة', category:'الفئة', gearbox:'ناقل الحركة', fuel:'الوقود', color:'اللون', licensePlate:'رقم اللوحة', odometer:'عداد المسافة', miles:'ميل', location:'الموقع', featuresLabel:'المميزات', pricing:'تسعير مرن', pricingText:'حدد سعراً مستقلاً لكل مدة.', image:'صورة الغلاف', cancel:'إلغاء', save:'حفظ التغييرات', create:'إضافة السيارة', saving:'جارٍ الحفظ…', confirmDelete:'هل تريد حذف هذه السيارة؟', deleteHint:'لا يمكن حذف السيارات التي لديها حجوزات حالية.', choosePhoto:'اختر صورة لعرض السيارة في السوق.',
  lifetimeRevenue:'إيرادات مدى الحياة', completedTripsLabel:'الرحلات المكتملة', currentBookings:'الحجوزات الحالية', completeVehicleRecord:'السجل الكامل لحجوزات هذه السيارة',
  rentalPipeline:'مسار الإيجارات', rentalPipelineText:'تابع كل طلب من التأكيد حتى إعادة السيارة.', all:'الكل', pending:'معلق', active:'نشط', completed:'مكتمل', cancelled:'ملغي', confirm:'تأكيد الطلب', complete:'إكمال الإيجار', cancelRental:'إلغاء الإيجار', noRentals:'لا توجد إيجارات هنا', noRentalsText:'ستظهر هنا الحجوزات بهذه الحالة.', customer:'العميل', vehicle:'السيارة', dates:'التواريخ', duration:'المدة', total:'الإجمالي', discount:'الخصم', company:'الشركة', reservation:'الحجز', billActions:'الفاتورة والإجراءات', proposal:'عرض السعر', bill:'الفاتورة', adjust:'تعديل', discounts:'خصومات', premiumService:'خدمة مميزة', premiumServicesCount:'خدمات مميزة', searchReservations:'ابحث في الحجوزات…',
  turnaroundTitle:'حماية ساعة تجهيز تلقائياً', turnaroundText:'يحجز كل طلب معلق أو نشط ساعة إضافية للفحص والتنظيف والصيانة والتزود بالوقود قبل الرحلة التالية.',
  adjustBill:'تعديل فاتورة الإيجار', premiumServiceLines:'بنود الخدمات المميزة', adminAdjustHint:'يمكن لمدير الشركة تعديل الأيام والسعر اليومي والخصومات.', catalogPrice:'سعر الكتالوج', priceDay:'السعر/اليوم', lineDiscount:'خصم البند', billSummary:'ملخص الفاتورة', vehicleRental:'إيجار السيارة', promotion:'العرض', additionalBillDiscount:'خصم إضافي على الفاتورة', updatedTotal:'الإجمالي المحدّث', updatedPdfHint:'تتوفر فاتورة PDF المحدّثة فوراً في حساب المستأجر.', saveIssueBill:'حفظ وإصدار الفاتورة المحدّثة', billUpdated:'تم تحديث الفاتورة ومشاركتها مع حساب المستأجر',
  promotionTitle:'العروض والخصومات', promotionText:'أنشئ عروضاً لكل الأسطول أو لسيارات محددة.', newPromotion:'عرض جديد', live:'مباشر', scheduled:'مجدول', expired:'منتهي', paused:'متوقف', redemptions:'استخدام', wholeFleet:'كامل الأسطول', selectedVehicles:'سيارات محددة', pause:'إيقاف', enable:'تفعيل', promoName:'اسم العرض', promoCode:'رمز العرض', discountType:'نوع الخصم', percentage:'نسبة مئوية', fixed:'مبلغ ثابت', value:'القيمة', starts:'تاريخ البداية', ends:'تاريخ النهاية', minimum:'الحد الأدنى للكمية', applies:'ينطبق على', launch:'إطلاق العرض', liveOffersGenerated:'حققت عروضك المباشرة', promoBookingsUp:'زادت الحجوزات الترويجية بنسبة 18٪ مقارنة بالشهر الماضي.', everyAvailableVehicle:'كل سيارة متاحة', chooseSpecificVehicles:'اختر سيارات محددة', campaignBuilder:'منشئ الحملات', offerInsights:'حققت عروضك المباشرة 7,840 دولاراً هذا الشهر', offerInsightsText:'ارتفعت حجوزات العروض بنسبة 18٪ مقارنة بالشهر الماضي.', entireFleetHint:'كل سيارة متاحة', selectedHint:'اختر سيارات محددة', editPromotion:'تعديل العرض', createPromotion:'إنشاء عرض',
  servicesEyebrow:'إضافات الإيجار', servicesPageText:'حدد السعر اليومي والتوفر. يمكن للمستأجرين اختيار عدد الأيام فقط.', addService:'إضافة خدمة', pricingControlTitle:'أنت تتحكم بالأسعار والخصومات', pricingControlText:'تُنسخ أسعار الكتالوج إلى كل عرض سعر. يمكن لمدير الشركة تعديل أيام الخدمة والسعر اليومي وخصومات البنود وخصم إضافي على الفاتورة. يمكن للمستأجر تغيير الأيام فقط.', pricePerServiceDay:'السعر لكل يوم خدمة', visibleRenters:'ظاهرة للمستأجرين', servicePaused:'متوقفة', serviceName:'اسم الخدمة', description:'الوصف', pricePerDay:'السعر في اليوم', serviceDescriptionPlaceholder:'صف ما سيحصل عليه المستأجر', serviceNamePlaceholder:'استقبال ومرافقة في المطار', addPremiumService:'إضافة خدمة مميزة', addServiceText:'أنشئ إضافة يومية جديدة للمستأجرين', serviceUpdated:'تم تحديث سعر الخدمة', serviceRemoved:'تم حذف الخدمة', serviceAdded:'تمت إضافة الخدمة المميزة', removeServiceConfirm:'ستحتفظ الفواتير السابقة بتفاصيل الخدمة المحفوظة.',
  findDrive:'اعثر على سيارتك المثالية', findDriveText:'احجز بالساعة أو اليوم أو الأسبوع أو الشهر.', searchCars:'ابحث عن سيارات…', priceView:'السعر المعروض', sortBy:'الترتيب حسب', priceLow:'السعر: من الأقل', newest:'الأحدث أولاً', rentNow:'استأجر الآن', noCars:'لا توجد سيارات مطابقة', noCarsText:'جرّب فئة أو ناقل حركة أو بحثاً مختلفاً.', clearFilters:'مسح المرشحات', pickupNear:'الاستلام بالقرب من', allGearboxes:'كل نواقل الحركة', off:'خصم', savedCar:'حفظ السيارة',
  everythingNeeded:'كل ما تحتاجه', protectedBooking:'حجز محمي · بدون رسوم خفية', noUpcomingBookings:'لا توجد حجوزات قادمة', turnaroundProtectedUntil:'وقت التجهيز محمي حتى', useCode:'استخدم',
  bookTitle:'أكمل حجزك', pickRate:'اختر نوع السعر', quantity:'الكمية', pickupTime:'وقت الاستلام', returnTime:'وقت الإعادة', promoOptional:'رمز عرض (اختياري)', apply:'تطبيق', promoApplied:'تم تطبيق العرض', subtotal:'المجموع الفرعي', confirmBooking:'تأكيد الحجز', busyPeriods:'الفترات المحجوزة', busyHint:'هذه السيارة محجوزة مسبقاً خلال هذه الفترات.', rentalDates:'تواريخ الإيجار', chooseDate:'اختر التاريخ', pickup:'الاستلام', returnDate:'تاريخ الإعادة', protectedTurnaround:'وقت تجهيز محمي للسيارة', protectedTurnaroundText:'يحفظ فليت فلو ساعة بين كل حجزين للفحص والتنظيف والصيانة والتزود بالوقود.', noBusyPeriods:'لا توجد فترات محجوزة قادمة', unavailableTime:'السيارة غير متاحة في وقت الاستلام المحدد', nextReady:'الموعد التالي بعد وقت التجهيز:', calendarDaysOpen:'يوم متاح قبل الحجز التالي', mustReturnBy:'يجب إعادة السيارة بحلول', serviceWindow:'لتحصل الشركة على ساعة التجهيز.', windowOpen:'الفترة المحددة متاحة', noLaterReservation:'لا يوجد حجز لاحق يحد هذه الفترة حالياً.', adjustedTurnaround:'تم تقديم الإعادة ساعة لوقت التجهيز', overlapDetected:'تم اكتشاف تداخل في الحجز', useAvailableRange:'استخدم الفترة المتاحة المنتهية في', customizeTrip:'خصص رحلتك', renterDaysOnly:'يمكنك تعديل أيام الخدمة فقط', numberDays:'عدد الأيام', rentalProposal:'عرض سعر الإيجار', pdfAfterConfirmation:'ستصدر فاتورة PDF مفصلة بعد التأكيد', bookingSent:'تم إصدار عرض سعر الإيجار وفاتورة PDF بنجاح', chooseRange:'اختر تاريخ البداية والنهاية من تقويم التوفر.', rangeReserved:'تصل الفترة المحددة إلى حجز قائم. اختر تاريخ إعادة أبكر.',
  calendarSelectDates:'اختر تواريخ الإيجار', calendarReservedHint:'يتم تعطيل التواريخ المحجوزة تلقائياً', open:'متاح', selected:'محدد', reserved:'محجوز', turnaround:'ساعة تجهيز', rangeCrossesReservation:'تتداخل هذه الفترة مع حجز قائم. لا يمكن تحديد التواريخ المحجوزة.',
  historyTitle:'سجل الإيجارات الكامل', historyText:'تابع رحلاتك القادمة والحالية والسابقة في مكان واحد.',
  welcomeBack:'مرحباً بعودتك', loginText:'سجّل الدخول للمتابعة إلى مساحة عملك.', email:'البريد الإلكتروني', password:'كلمة المرور', remember:'تذكرني', forgot:'نسيت كلمة المرور؟', newHere:'جديد في فليت فلو؟', createAccount:'إنشاء حساب', demoAccounts:'جرّب حساباً تجريبياً', renter:'مستأجر', companyRole:'شركة', join:'انضم إلى فليت فلو', registerText:'أنشئ ملف مستأجر أو مساحة عمل لشركة.', fullName:'الاسم الكامل', companyName:'اسم الشركة', haveAccount:'لديك حساب بالفعل؟', builtJourney:'مصمم لكل رحلة', driveFuture:'قد مستقبل التنقل.', fleetForward:'أسطولك. طريقك نحو الأمام.', authText:'منصة واحدة مترابطة لإيجارات استثنائية وأسعار مرنة وإدارة أسطول سهلة.', authAvailability:'توفر مباشر وحجوزات محمية', authRates:'أسعار مرنة من الساعة إلى الشهر', authTrust:'شركات موثوقة وسجل شفاف', verifiedFleet:'أسطول موثّق', premiumCars:'17 سيارة مميزة', legalText:'بمتابعتك، فإنك توافق على شروط فليت فلو وسياسة الخصوصية.',
  invoiceBack:'العودة إلى الإيجارات', pdf:'PDF', emailAction:'البريد', whatsapp:'واتساب', print:'طباعة', issued:'تاريخ الإصدار', issuedBy:'صادرة عن', billedTo:'محررة إلى', rentedVehicle:'السيارة المستأجرة', transmission:'ناقل الحركة', detailedBreakdown:'تفاصيل الإيجار', descriptionColumn:'الوصف', amount:'المبلغ', totalDue:'الإجمالي المستحق', billAdjustment:'تعديل الفاتورة', invoiceProtection:'إيجار محمي من فليت فلو', invoiceProtectionText:'تشمل هذه الفاتورة السيارة والجدول والعرض والخدمات المميزة وتعديلات الشركة.', thankYou:'شكراً لاختيارك فليت فلو.', shareDownloaded:'تم تنزيل PDF. أرفقه في المحادثة المفتوحة.', rentalInvoice:'فاتورة إيجار', rentalProposalDoc:'عرض سعر إيجار', pickupLocation:'موقع الاستلام', ratePlan:'خطة السعر', vehicleDiscount:'خصم السيارة', serviceDiscount:'خصم الخدمة', additionalCompanyDiscount:'خصم إضافي من الشركة', totalDiscounts:'إجمالي الخصومات', invoiceRentalSuffix:'إيجار', unablePreparePdf:'تعذر تجهيز ملف PDF', rentalBillReady:'فاتورة إيجارك من فليت فلو جاهزة. تم تنزيل PDF لإرفاقه. يمكنك أيضاً عرضها هنا:',
  loading:'جارٍ التحميل…', close:'إغلاق', All:'الكل', to:'إلى', use:'استخدم', everythingNeed:'كل ما تحتاجه', tryDifferentFilters:'جرّب فئة أو ناقل حركة أو بحثاً مختلفاً.', turnaroundUntil:'وقت التجهيز محمي حتى', tryAgain:'حاول مجدداً', saved:'تم الحفظ', copied:'تم النسخ', theme:'المظهر', language:'اللغة', system:'النظام', light:'فاتح', dark:'داكن', saveAction:'حفظ', add:'إضافة', remove:'حذف', search:'بحث',
  'Luxury sedan':'سيدان فاخرة', Executive:'تنفيذية', 'Premium SUV':'دفع رباعي مميزة', 'Electric SUV':'دفع رباعي كهربائية', Sedan:'سيدان', Performance:'رياضية', SUV:'دفع رباعي', 'Luxury SUV':'دفع رباعي فاخرة', 'Electric sedan':'سيدان كهربائية',
  Automatic:'أوتوماتيك', Manual:'يدوي', Hybrid:'هجين', Electric:'كهربائي', Petrol:'بنزين', Diesel:'ديزل',
  'GPS':'نظام تحديد المواقع', 'Heated seats':'مقاعد مدفأة', 'Apple CarPlay':'آبل كار بلاي', 'Premium audio':'نظام صوتي مميز', '360° camera':'كاميرا 360°', 'Virtual cockpit':'قمرة قيادة افتراضية', 'Adaptive cruise':'مثبت سرعة متكيف', CarPlay:'كار بلاي', 'Lane assist':'مساعد المسار', 'Keyless entry':'دخول بدون مفتاح', 'Pilot assist':'مساعد القيادة', 'Panoramic roof':'سقف بانورامي', '7 seats':'7 مقاعد', 'Blind spot assist':'مساعد النقطة العمياء', 'Massage seats':'مقاعد تدليك', 'Meridian audio':'نظام ميريديان الصوتي', 'Chauffeur package':'باقة السائق', 'Burmester audio':'نظام بورمستر الصوتي', 'Sky lounge':'صالة سماوية', 'Parking assist':'مساعد الركن', 'Sport chrono':'سبورت كرونو', 'BOSE audio':'نظام بوز الصوتي', 'Adaptive suspension':'تعليق متكيف', 'Matrix LED':'مصابيح ماتريكس LED', 'Bang & Olufsen':'بانغ آند أولفسن', 'Air suspension':'تعليق هوائي', Autopilot:'قيادة آلية', 'Supercharger access':'إمكانية استخدام الشاحن الفائق', 'Glass roof':'سقف زجاجي', 'Premium connectivity':'اتصال مميز', 'Google built-in':'جوجل مدمج', 'Pilot pack':'حزمة القيادة', 'Harman Kardon':'هارمان كاردون', 'Vehicle-to-load':'تزويد الأجهزة بالطاقة من السيارة', 'Highway assist':'مساعد الطريق السريع', 'Ultra-fast charging':'شحن فائق السرعة', 'Relaxation seats':'مقاعد استرخاء', 'Driving assistant':'مساعد القيادة',
  'Professional driver':'سائق محترف', 'Executive chauffeur':'سائق تنفيذي', 'EV-trained driver':'سائق مدرّب على السيارات الكهربائية', 'Loading & offloading help':'مساعدة تحميل وتنزيل الأمتعة', 'Luggage concierge':'خدمة الأمتعة', 'Child safety seat':'مقعد أمان للطفل', 'Premium child seat':'مقعد طفل مميز', 'In-car Wi-Fi':'واي فاي داخل السيارة', 'Executive Wi-Fi':'واي فاي تنفيذي', 'Connected car Wi-Fi':'واي فاي للسيارة المتصلة', driverDescription:'سائق خاص مرخص للرحلات المحلية أو الطويلة.', luggageDescription:'مساعد مدرّب لتحميل الأمتعة وتنزيلها بأمان.', childSeatDescription:'مقعد أطفال نظيف ومفحوص يُركّب قبل الاستلام.', wifiDescription:'واي فاي متنقل عالي السرعة وغير محدود طوال الرحلة.',
};

const dictionaries = { en, ar };
const I18n = createContext<{ lang: Lang; t: (key: string) => string; setLang: (lang: Lang) => void }>({ lang:'en', t:key=>key, setLang:()=>{} });

export function I18nProvider({ initialLang, children }: { initialLang: Lang; children: React.ReactNode }) {
  const [lang, setState] = useState<Lang>(initialLang);
  const setLang = (next: Lang) => {
    document.cookie = `ff_lang=${next};path=/;max-age=31536000;samesite=lax`;
    document.documentElement.lang = next;
    document.documentElement.dir = next === 'ar' ? 'rtl' : 'ltr';
    setState(next);
  };
  return <I18n.Provider value={{ lang, t:(key)=>dictionaries[lang][key] || en[key] || key, setLang }}>{children}</I18n.Provider>;
}
export const useI18n = () => useContext(I18n);
