'use client';
import { createContext, useContext, useState } from 'react';

type Lang='en'|'ar';
const en:Record<string,string>={
  brand:'FleetFlow',marketplace:'Marketplace',deals:'Deals',features:'Features',signIn:'Sign in',getStarted:'Get started',
  heroEyebrow:'The smarter way to rent and manage',heroTitle:'Every journey, perfectly managed.',heroText:'Book exceptional cars with complete flexibility—or run your entire rental fleet from one calm, connected workspace.',browseCars:'Browse cars',listFleet:'List your fleet',liveVehicles:'live vehicles',trustedCompanies:'trusted companies',completedTrips:'completed trips',
  featured:'Featured vehicles',featuredText:'Curated drives from trusted local companies.',viewAll:'View all',from:'from',day:'day',hour:'hour',week:'week',month:'month',
  flexibleTitle:'Built around the way you move',flexibleText:'From one hour downtown to a month on the coast, choose exactly the time you need.',smartBooking:'Smart booking',smartBookingText:'Live availability, instant pricing, and protected reservations.',trustedFleet:'Trusted fleet',trustedFleetText:'Verified companies, maintained vehicles, and transparent history.',realSavings:'Real savings',realSavingsText:'Live deals appear automatically on every eligible vehicle.',
  readyTitle:'Ready to move differently?',readyText:'Join thousands of drivers and modern mobility teams already using FleetFlow.',exploreFleet:'Explore the fleet',
  overview:'Overview',fleet:'Fleet',rentals:'Rentals',promotions:'Promotions',premiumServices:'Premium services',browse:'Browse cars',settings:'Settings',support:'Help & support',workspace:'Workspace',administrator:'Administrator',verifiedDriver:'Verified driver',logout:'Sign out',
  goodMorning:'Good morning',overviewText:'Here is what is moving across your business today.',grossRevenue:'Gross revenue',pendingRequests:'Pending requests',activeRentals:'Active rentals',fleetSize:'Fleet size',monthlyRevenue:'Monthly revenue',utilization:'Fleet utilization',recentRentals:'Recent rentals',viewPipeline:'View pipeline',availability:'Availability',available:'Available',maintenance:'Maintenance',retired:'Retired',
  myNextDrive:'Your next drive starts here',whereNext:'Where will you go next?',upcomingTrips:'Upcoming trips',totalRentals:'Total rentals',lifetimeSpend:'Lifetime spend',loyalty:'Loyalty status',goldDriver:'Gold driver',currentRental:'Current rental',recommended:'Recommended for you',
  manageFleet:'Manage vehicles, pricing, and availability in one place.',addVehicle:'Add vehicle',searchFleet:'Search make, model, or plate…',allStatuses:'All statuses',edit:'Edit',delete:'Delete',details:'Details',rentalHistory:'Rental history',per:'per',seats:'seats',automatic:'Automatic',noVehicles:'No vehicles found',noVehiclesText:'Try another filter or add a new vehicle to your fleet.',
  vehicleDetails:'Vehicle details',basicInformation:'Basic information and specifications.',make:'Make',model:'Model',year:'Year',category:'Category',gearbox:'Gearbox',fuel:'Fuel',color:'Color',licensePlate:'License plate',odometer:'Odometer',location:'Location',featuresLabel:'Features',pricing:'Flexible pricing',pricingText:'Set an independent price for every duration.',image:'Cover image',cancel:'Cancel',save:'Save changes',create:'Add vehicle',saving:'Saving…',confirmDelete:'Delete this vehicle?',deleteHint:'Vehicles with current bookings cannot be deleted.',
  rentalPipeline:'Rental pipeline',rentalPipelineText:'Move every request from confirmation to return.',all:'All',pending:'Pending',active:'Active',completed:'Completed',cancelled:'Cancelled',confirm:'Confirm request',complete:'Complete rental',cancelRental:'Cancel rental',noRentals:'No rentals here',noRentalsText:'Bookings in this state will appear here.',customer:'Customer',vehicle:'Vehicle',dates:'Dates',duration:'Duration',total:'Total',discount:'Discount',company:'Company',
  promotionTitle:'Promotions & discounts',promotionText:'Create targeted offers for your whole fleet or selected vehicles.',newPromotion:'New promotion',live:'Live',scheduled:'Scheduled',expired:'Expired',paused:'Paused',redemptions:'redemptions',wholeFleet:'Whole fleet',selectedVehicles:'Selected vehicles',pause:'Pause',enable:'Enable',promoName:'Promotion name',promoCode:'Promo code',discountType:'Discount type',percentage:'Percentage',fixed:'Fixed amount',value:'Value',starts:'Starts on',ends:'Ends on',minimum:'Minimum quantity',applies:'Applies to',launch:'Launch promotion',
  findDrive:'Find your perfect drive',findDriveText:'Book by the hour, day, week, or month.',searchCars:'Search cars…',priceView:'Displayed price',sortBy:'Sort by',priceLow:'Price: low to high',newest:'Newest first',rentNow:'Rent now',noCars:'No cars match your filters',clearFilters:'Clear filters',
  bookTitle:'Complete your booking',pickRate:'Choose a rate type',quantity:'Quantity',pickupTime:'Pick-up time',returnTime:'Return time',promoOptional:'Promo code (optional)',apply:'Apply',promoApplied:'Promotion applied',subtotal:'Subtotal',confirmBooking:'Confirm booking',busyPeriods:'Busy periods',busyHint:'This vehicle is already reserved during these windows.',
  historyTitle:'Complete rental history',historyText:'Track upcoming, current, and past drives in one place.',
  welcomeBack:'Welcome back',loginText:'Sign in to continue to your workspace.',email:'Email address',password:'Password',remember:'Remember me',forgot:'Forgot password?',newHere:'New to FleetFlow?',createAccount:'Create account',demoAccounts:'Try a demo account',renter:'Renter',companyRole:'Company',
  join:'Join FleetFlow',registerText:'Create a renter profile or company workspace.',fullName:'Full name',companyName:'Company name',haveAccount:'Already have an account?',
  loading:'Loading…',tryAgain:'Try again',saved:'Saved',copied:'Copied',theme:'Theme',language:'Language',system:'System',light:'Light',dark:'Dark',
};
const ar:Record<string,string>={
  brand:'فليت فلو',marketplace:'سوق السيارات',deals:'العروض',features:'المميزات',signIn:'تسجيل الدخول',getStarted:'ابدأ الآن',
  heroEyebrow:'الطريقة الأذكى للتأجير والإدارة',heroTitle:'كل رحلة، بإدارة مثالية.',heroText:'احجز سيارات استثنائية بمرونة كاملة — أو أدر أسطول التأجير بالكامل من مساحة عمل هادئة ومتكاملة.',browseCars:'تصفح السيارات',listFleet:'أضف أسطولك',liveVehicles:'سيارة متاحة',trustedCompanies:'شركة موثوقة',completedTrips:'رحلة مكتملة',
  featured:'سيارات مميزة',featuredText:'سيارات مختارة من شركات محلية موثوقة.',viewAll:'عرض الكل',from:'ابتداءً من',day:'يوم',hour:'ساعة',week:'أسبوع',month:'شهر',
  flexibleTitle:'مصمم ليناسب طريقة تنقلك',flexibleText:'من ساعة واحدة في المدينة إلى شهر على الساحل، اختر المدة التي تحتاجها بالضبط.',smartBooking:'حجز ذكي',smartBookingText:'توفر مباشر وأسعار فورية وحجوزات محمية.',trustedFleet:'أسطول موثوق',trustedFleetText:'شركات موثقة وسيارات مصانة وسجل شفاف.',realSavings:'توفير حقيقي',realSavingsText:'تظهر العروض المباشرة تلقائياً على كل سيارة مؤهلة.',
  readyTitle:'جاهز لتتحرك بطريقة مختلفة؟',readyText:'انضم إلى آلاف السائقين وشركات التنقل الحديثة التي تستخدم فليت فلو.',exploreFleet:'استكشف الأسطول',
  overview:'نظرة عامة',fleet:'الأسطول',rentals:'الإيجارات',promotions:'العروض',premiumServices:'الخدمات المميزة',browse:'تصفح السيارات',settings:'الإعدادات',support:'المساعدة والدعم',workspace:'مساحة العمل',administrator:'مدير النظام',verifiedDriver:'سائق موثق',logout:'تسجيل الخروج',
  goodMorning:'صباح الخير',overviewText:'إليك حركة أعمالك اليوم.',grossRevenue:'إجمالي الإيرادات',pendingRequests:'طلبات معلقة',activeRentals:'إيجارات نشطة',fleetSize:'حجم الأسطول',monthlyRevenue:'الإيرادات الشهرية',utilization:'استخدام الأسطول',recentRentals:'أحدث الإيجارات',viewPipeline:'عرض المسار',availability:'حالة التوفر',available:'متاحة',maintenance:'قيد الصيانة',retired:'متقاعدة',
  myNextDrive:'رحلتك القادمة تبدأ هنا',whereNext:'إلى أين ستكون رحلتك القادمة؟',upcomingTrips:'رحلات قادمة',totalRentals:'إجمالي الإيجارات',lifetimeSpend:'إجمالي الإنفاق',loyalty:'حالة الولاء',goldDriver:'سائق ذهبي',currentRental:'الإيجار الحالي',recommended:'مقترحة لك',
  manageFleet:'أدر السيارات والأسعار والتوفر من مكان واحد.',addVehicle:'إضافة سيارة',searchFleet:'ابحث بالماركة أو الموديل أو اللوحة…',allStatuses:'كل الحالات',edit:'تعديل',delete:'حذف',details:'التفاصيل',rentalHistory:'سجل الإيجار',per:'لكل',seats:'مقاعد',automatic:'أوتوماتيك',noVehicles:'لا توجد سيارات',noVehiclesText:'جرّب مرشحاً آخر أو أضف سيارة جديدة إلى أسطولك.',
  vehicleDetails:'تفاصيل السيارة',basicInformation:'المعلومات الأساسية والمواصفات.',make:'الماركة',model:'الموديل',year:'السنة',category:'الفئة',gearbox:'ناقل الحركة',fuel:'الوقود',color:'اللون',licensePlate:'رقم اللوحة',odometer:'عداد المسافة',location:'الموقع',featuresLabel:'المميزات',pricing:'تسعير مرن',pricingText:'حدد سعراً مستقلاً لكل مدة.',image:'صورة الغلاف',cancel:'إلغاء',save:'حفظ التغييرات',create:'إضافة السيارة',saving:'جارٍ الحفظ…',confirmDelete:'هل تريد حذف هذه السيارة؟',deleteHint:'لا يمكن حذف السيارات التي لديها حجوزات حالية.',
  rentalPipeline:'مسار الإيجارات',rentalPipelineText:'تابع كل طلب من التأكيد حتى إعادة السيارة.',all:'الكل',pending:'معلق',active:'نشط',completed:'مكتمل',cancelled:'ملغي',confirm:'تأكيد الطلب',complete:'إكمال الإيجار',cancelRental:'إلغاء الإيجار',noRentals:'لا توجد إيجارات هنا',noRentalsText:'ستظهر هنا الحجوزات بهذه الحالة.',customer:'العميل',vehicle:'السيارة',dates:'التواريخ',duration:'المدة',total:'الإجمالي',discount:'الخصم',company:'الشركة',
  promotionTitle:'العروض والخصومات',promotionText:'أنشئ عروضاً لكل الأسطول أو لسيارات محددة.',newPromotion:'عرض جديد',live:'مباشر',scheduled:'مجدول',expired:'منتهي',paused:'متوقف',redemptions:'استخدام',wholeFleet:'كامل الأسطول',selectedVehicles:'سيارات محددة',pause:'إيقاف',enable:'تفعيل',promoName:'اسم العرض',promoCode:'رمز العرض',discountType:'نوع الخصم',percentage:'نسبة مئوية',fixed:'مبلغ ثابت',value:'القيمة',starts:'تاريخ البداية',ends:'تاريخ النهاية',minimum:'الحد الأدنى للكمية',applies:'ينطبق على',launch:'إطلاق العرض',
  findDrive:'اعثر على سيارتك المثالية',findDriveText:'احجز بالساعة أو اليوم أو الأسبوع أو الشهر.',searchCars:'ابحث عن سيارات…',priceView:'السعر المعروض',sortBy:'الترتيب حسب',priceLow:'السعر: من الأقل',newest:'الأحدث أولاً',rentNow:'استأجر الآن',noCars:'لا توجد سيارات مطابقة',clearFilters:'مسح المرشحات',
  bookTitle:'أكمل حجزك',pickRate:'اختر نوع السعر',quantity:'الكمية',pickupTime:'وقت الاستلام',returnTime:'وقت الإعادة',promoOptional:'رمز عرض (اختياري)',apply:'تطبيق',promoApplied:'تم تطبيق العرض',subtotal:'المجموع الفرعي',confirmBooking:'تأكيد الحجز',busyPeriods:'الفترات المحجوزة',busyHint:'هذه السيارة محجوزة مسبقاً خلال هذه الفترات.',
  historyTitle:'سجل الإيجارات الكامل',historyText:'تابع رحلاتك القادمة والحالية والسابقة في مكان واحد.',
  welcomeBack:'مرحباً بعودتك',loginText:'سجّل الدخول للمتابعة إلى مساحة عملك.',email:'البريد الإلكتروني',password:'كلمة المرور',remember:'تذكرني',forgot:'نسيت كلمة المرور؟',newHere:'جديد في فليت فلو؟',createAccount:'إنشاء حساب',demoAccounts:'جرّب حساباً تجريبياً',renter:'مستأجر',companyRole:'شركة',
  join:'انضم إلى فليت فلو',registerText:'أنشئ ملف مستأجر أو مساحة عمل لشركة.',fullName:'الاسم الكامل',companyName:'اسم الشركة',haveAccount:'لديك حساب بالفعل؟',
  loading:'جارٍ التحميل…',tryAgain:'حاول مجدداً',saved:'تم الحفظ',copied:'تم النسخ',theme:'المظهر',language:'اللغة',system:'النظام',light:'فاتح',dark:'داكن',
};
const dictionaries={en,ar};
const I18n=createContext<{lang:Lang;t:(key:string)=>string;setLang:(lang:Lang)=>void}>({lang:'en',t:k=>k,setLang:()=>{}});
export function I18nProvider({initialLang,children}:{initialLang:Lang;children:React.ReactNode}){const[lang,setState]=useState<Lang>(initialLang);const setLang=(next:Lang)=>{document.cookie=`ff_lang=${next};path=/;max-age=31536000;samesite=lax`;document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';setState(next)};return <I18n.Provider value={{lang,t:(key)=>dictionaries[lang][key]||en[key]||key,setLang}}>{children}</I18n.Provider>}
export const useI18n=()=>useContext(I18n);
