import type { Lang } from './i18n';

export type ContentSection = { title:string; body:string; bullets?:string[] };

export const publicFaqs:Record<Lang,Array<{category:string;question:string;answer:string}>> = {
  en:[
    { category:'Getting started', question:'Can I browse vehicles without creating an account?', answer:'Yes. The public marketplace, vehicle specifications, pickup cities, rates, promotions, protection options, and busy periods are available before sign-in. An account is required only when you start a rental.' },
    { category:'Account access', question:'How can I sign in?', answer:'Renters can use email and password, Google, Facebook, or a verification code delivered through WhatsApp. Company workspaces can use their registered account credentials.' },
    { category:'Companies', question:'How does a rental company join FleetFlow?', answer:'Choose “List your fleet” on the home page and create a company workspace. The company remains responsible for its operating licenses, vehicle documents, insurance, rates, inventory, and rental contracts in each market.' },
    { category:'Marketplace', question:'Does FleetFlow own or rent the listed vehicles?', answer:'No. FleetFlow provides marketplace and fleet-management technology. Each vehicle is offered by the rental company identified on its listing and contract.' },
    { category:'Platform support', question:'What should I report using this public support form?', answer:'Use it for FleetFlow website or app problems, account-access questions, privacy requests, legal inquiries, platform suggestions, partnerships, and general feedback.' },
    { category:'Rental support', question:'Where should I report a booking, vehicle, pickup, payment, or accident issue?', answer:'Those issues must go to the responsible rental company. Sign in and use the rental-linked support conversation so the correct company receives the booking context. For emergencies, contact the competent local authority first.' },
    { category:'Markets', question:'Does FleetFlow use the same conditions in Saudi Arabia and Yemen?', answer:'Core platform conditions apply everywhere, with separate market schedules. Saudi rentals must follow applicable Transport General Authority, insurance, tax, and data-protection requirements. Yemen rentals remain subject to applicable licensing, traffic, vehicle, insurance, tax, and contract requirements and local authority instructions.' },
    { category:'Privacy', question:'How can I request access, correction, or deletion of my data?', answer:'Submit a Privacy request below or use your signed-in support center. We verify identity before acting and may retain records when a contract, safety obligation, legal claim, or applicable law requires it.' },
  ],
  ar:[
    { category:'البدء', question:'هل يمكنني تصفح السيارات دون إنشاء حساب؟', answer:'نعم. يمكنك مشاهدة السوق العام ومواصفات السيارات ومدن الاستلام والأسعار والعروض وخيارات الحماية وفترات الانشغال قبل تسجيل الدخول. لا يُطلب الحساب إلا عند بدء الإيجار.' },
    { category:'الدخول للحساب', question:'كيف يمكنني تسجيل الدخول؟', answer:'يمكن للمستأجر استخدام البريد وكلمة المرور أو جوجل أو فيسبوك أو رمز تحقق يصل عبر واتساب. وتستخدم الشركات بيانات حساب مساحة العمل المسجلة.' },
    { category:'الشركات', question:'كيف تنضم شركة تأجير إلى فليت فلو؟', answer:'اختر «أدرج أسطولك» في الصفحة الرئيسية وأنشئ مساحة عمل للشركة. تبقى الشركة مسؤولة عن تراخيص النشاط ووثائق السيارات والتأمين والأسعار والمخزون وعقود الإيجار في كل سوق.' },
    { category:'السوق', question:'هل تمتلك فليت فلو السيارات المعروضة أو تؤجرها؟', answer:'لا. توفر فليت فلو تقنية السوق وإدارة الأسطول. كل سيارة تقدمها شركة التأجير المبينة في الإعلان والعقد.' },
    { category:'دعم المنصة', question:'ما الذي أبلّغ عنه من خلال نموذج الدعم العام؟', answer:'استخدمه لمشكلات موقع أو تطبيق فليت فلو وأسئلة الوصول للحساب وطلبات الخصوصية والاستفسارات القانونية والاقتراحات والشراكات والملاحظات العامة.' },
    { category:'دعم الإيجار', question:'أين أبلغ عن مشكلة حجز أو سيارة أو استلام أو دفع أو حادث؟', answer:'ترسل هذه المسائل إلى شركة التأجير المسؤولة. سجّل الدخول واستخدم محادثة الدعم المرتبطة بالإيجار كي تصل التفاصيل إلى الشركة الصحيحة. وفي الطوارئ تواصل أولاً مع الجهة المحلية المختصة.' },
    { category:'الأسواق', question:'هل تطبق فليت فلو الشروط نفسها في السعودية واليمن؟', answer:'تطبق شروط المنصة الأساسية في كل مكان مع ملاحق مستقلة لكل سوق. تخضع الإيجارات السعودية لمتطلبات الهيئة العامة للنقل والتأمين والضرائب وحماية البيانات المطبقة. وتخضع إيجارات اليمن لمتطلبات الترخيص والمرور والمركبات والتأمين والضرائب والعقود وتعليمات السلطات المحلية النافذة.' },
    { category:'الخصوصية', question:'كيف أطلب الوصول إلى بياناتي أو تصحيحها أو حذفها؟', answer:'أرسل طلب خصوصية أدناه أو استخدم مركز الدعم بعد تسجيل الدخول. نتحقق من الهوية قبل التنفيذ وقد نحتفظ ببعض السجلات إذا تطلبها عقد أو التزام سلامة أو مطالبة قانونية أو نظام نافذ.' },
  ],
};

export const privacySections:Record<Lang,ContentSection[]> = {
  en:[
    { title:'1. Who this notice covers', body:'This notice explains how FleetFlow processes personal data when visitors browse the marketplace, create an account, manage a company workspace, make or service a rental, use WhatsApp or social sign-in, contact platform support, or open an invoice share link.' },
    { title:'2. Data we collect', body:'We collect only data reasonably needed to operate, secure, and improve the platform.', bullets:['Identity and contact data such as name, email, phone number, account role, and profile details.','Authentication data, including password hashes, session records, OAuth account identifiers, and hashed one-time verification codes.','Rental and contract data such as selected vehicle, locations, dates, services, protection, prices, invoices, odometer acknowledgements, and support messages.','Company and fleet data such as business identity, vehicles, plates, VINs, insurance, locations, telemetry, maintenance, and billing records.','Technical data such as request time, browser/device signals, security logs, language, theme, and privacy-preserving rate-limit identifiers.'] },
    { title:'3. Why we use data', body:'We use data to provide marketplace and workspace functions, authenticate users, protect reservations, calculate bills, generate documents, route support, prevent fraud and abuse, keep audit records, comply with lawful obligations, and improve reliability. We do not sell personal data.' },
    { title:'4. Rental companies and other recipients', body:'FleetFlow shares rental data with the company offering the selected vehicle because that company must fulfill and administer the rental. Data may also be processed by infrastructure, messaging, OAuth, document, security, and professional-service providers under appropriate controls. We disclose information to competent authorities when legally required.' },
    { title:'5. Saudi Arabia privacy schedule', body:'For individuals in Saudi Arabia, FleetFlow applies the Saudi Personal Data Protection Law and its Implementing Regulations where applicable. Rights may include being informed, access, obtaining a readable copy, correction, destruction where permitted, and withdrawal of consent where consent is the basis. Cross-border processing is assessed under applicable Saudi requirements.' },
    { title:'6. Yemen privacy schedule', body:'For Yemen-related use, FleetFlow follows applicable Yemeni law and privacy principles including purpose limitation, confidentiality, reasonable security, data accuracy, restricted disclosure, and access/correction where applicable. Yemen’s Right of Access to Information Law includes privacy protections for personal data held by covered entities; FleetFlow applies the protections stated in this notice to platform processing regardless of whether a specific statutory provision applies to a particular private transaction.' },
    { title:'7. Retention', body:'We keep account, contract, invoice, odometer, payment, insurance, maintenance, safety, and support records only as long as reasonably needed for service, legal, tax, audit, dispute, fraud-prevention, or regulatory purposes. Expired verification codes are removed on a rolling basis. Data is deleted or anonymized when retention is no longer justified.' },
    { title:'8. Security', body:'FleetFlow uses role isolation, signed sessions, password and OTP hashing, one-use codes, request throttling, database constraints, minimized public responses, and operational audit records. No system can guarantee absolute security; report a suspected platform vulnerability through Public Support and do not include exploit details in a public channel.' },
    { title:'9. Your choices and rights', body:'You can update many profile and preference fields in Settings. For access, correction, deletion/destruction, objection, consent withdrawal, portability/copy, or complaint requests, contact Platform Support and select Privacy. We verify identity and respond according to applicable law; exceptions may apply to contracts, claims, safety records, and legal retention.' },
    { title:'10. Contact and updates', body:'Contact FleetFlow platform management through /support or support@fleetflow.app. This notice may be updated when services, providers, or legal requirements change. Material changes will be identified by a revised effective date.' },
  ],
  ar:[
    { title:'1. نطاق إشعار الخصوصية', body:'يوضح هذا الإشعار كيفية معالجة فليت فلو للبيانات الشخصية عند تصفح السوق أو إنشاء حساب أو إدارة مساحة شركة أو إنشاء وخدمة إيجار أو استخدام واتساب أو تسجيل الدخول الاجتماعي أو التواصل مع دعم المنصة أو فتح رابط فاتورة مشترك.' },
    { title:'2. البيانات التي نجمعها', body:'نجمع فقط البيانات اللازمة بصورة معقولة لتشغيل المنصة وتأمينها وتحسينها.', bullets:['بيانات الهوية والتواصل مثل الاسم والبريد ورقم الهاتف ودور الحساب وبيانات الملف.','بيانات المصادقة، ومنها تجزئات كلمات المرور وسجلات الجلسات ومعرفات حسابات OAuth ورموز التحقق المجزأة.','بيانات الإيجار والعقد مثل السيارة والمواقع والتواريخ والخدمات والحماية والأسعار والفواتير وإقرارات العداد ورسائل الدعم.','بيانات الشركة والأسطول مثل هوية النشاط والسيارات واللوحات وأرقام الهيكل والتأمين والمواقع والقياس والصيانة والفوترة.','بيانات تقنية مثل وقت الطلب وإشارات المتصفح والجهاز وسجلات الأمان واللغة والمظهر ومعرفات تحديد المعدل المحافظة على الخصوصية.'] },
    { title:'3. أغراض الاستخدام', body:'نستخدم البيانات لتقديم وظائف السوق ومساحة العمل وتوثيق المستخدمين وحماية الحجوزات وحساب الفواتير وإنشاء المستندات وتوجيه الدعم ومنع الاحتيال وإساءة الاستخدام والاحتفاظ بسجلات التدقيق والامتثال للالتزامات النظامية وتحسين الاعتمادية. لا نبيع البيانات الشخصية.' },
    { title:'4. شركات التأجير والجهات المستلمة', body:'تشارك فليت فلو بيانات الإيجار مع الشركة التي تعرض السيارة المختارة لأنها المسؤولة عن تنفيذ الإيجار وإدارته. وقد يعالج البيانات مزودو البنية التحتية والمراسلة وتسجيل الدخول والمستندات والأمن والخدمات المهنية وفق ضوابط مناسبة. ونفصح للسلطات المختصة عندما يوجب النظام ذلك.' },
    { title:'5. ملحق الخصوصية للسعودية', body:'بالنسبة للأفراد في المملكة العربية السعودية، تطبق فليت فلو نظام حماية البيانات الشخصية ولائحته التنفيذية حيثما ينطبق. وقد تشمل الحقوق العلم والوصول والحصول على نسخة مقروءة والتصحيح والإتلاف حيث يسمح النظام وسحب الموافقة عندما تكون أساس المعالجة. وتُقيّم المعالجة عبر الحدود وفق المتطلبات السعودية المطبقة.' },
    { title:'6. ملحق الخصوصية لليمن', body:'للاستخدام المرتبط باليمن، تتبع فليت فلو القانون اليمني النافذ ومبادئ تحديد الغرض والسرية والأمن المعقول ودقة البيانات وتقييد الإفصاح والوصول والتصحيح حيثما ينطبق. ويتضمن قانون حق الحصول على المعلومات اليمني أحكاماً لحماية البيانات الشخصية لدى الجهات المشمولة؛ وتطبق فليت فلو الحماية الواردة في هذا الإشعار على معالجة المنصة بصرف النظر عن انطباق نص بعينه على معاملة خاصة.' },
    { title:'7. مدة الاحتفاظ', body:'نحتفظ بسجلات الحساب والعقد والفاتورة والعداد والدفع والتأمين والصيانة والسلامة والدعم فقط للمدة اللازمة بصورة معقولة للخدمة أو النظام أو الضرائب أو التدقيق أو النزاع أو منع الاحتيال أو التنظيم. تُزال رموز التحقق المنتهية دورياً، وتحذف البيانات أو تُجهّل عند انتهاء مبرر الاحتفاظ.' },
    { title:'8. الأمان', body:'تستخدم فليت فلو عزل الأدوار والجلسات الموقعة وتجزئة كلمات المرور والرموز والرموز أحادية الاستخدام وتحديد المعدل وقيود قاعدة البيانات وتقليل البيانات العامة وسجلات التشغيل. لا يوجد نظام يضمن أماناً مطلقاً؛ أبلغ عن الاشتباه بثغرة عبر الدعم العام ولا تضع تفاصيل الاستغلال في قناة عامة.' },
    { title:'9. خياراتك وحقوقك', body:'يمكنك تحديث كثير من بيانات الملف والتفضيلات من الإعدادات. ولطلبات الوصول أو التصحيح أو الحذف/الإتلاف أو الاعتراض أو سحب الموافقة أو النسخة أو الشكوى، تواصل مع دعم المنصة واختر الخصوصية. نتحقق من الهوية ونستجيب وفق القانون النافذ، وقد تنطبق استثناءات للعقود والمطالبات وسجلات السلامة والاحتفاظ النظامي.' },
    { title:'10. التواصل والتحديثات', body:'تواصل مع إدارة منصة فليت فلو عبر /support أو support@fleetflow.app. قد نحدث هذا الإشعار عند تغير الخدمات أو المزودين أو المتطلبات القانونية، وتظهر التغييرات المهمة بتاريخ نفاذ محدث.' },
  ],
};

export const commonTerms:Record<Lang,ContentSection[]> = {
  en:[
    { title:'1. Platform role', body:'FleetFlow provides marketplace, booking, document, communication, and fleet-operations technology. Unless FleetFlow is expressly identified as the vehicle provider in a contract, the rental company—not FleetFlow—owns or controls the vehicle and is the lessor responsible for fulfillment.' },
    { title:'2. Accounts and authority', body:'Users must provide accurate information, protect account access, and use only identities and company workspaces they are authorized to use. Company administrators confirm they have authority to publish vehicles, policies, prices, documents, and contract terms for their business.' },
    { title:'3. Listings and rental contracts', body:'A listing is not a rental contract. The binding rental terms are the confirmed proposal/contract, applicable company terms, market schedule, and mandatory law. Companies are responsible for listing accuracy, vehicle availability, operating authority, insurance, roadworthiness, and lawful taxes and charges.' },
    { title:'4. Prices, mileage, fuel, and additions', body:'Before booking, the renter sees rates, promotions, services, protection, locations, fuel terms, daily kilometer allowance, and the fee per excess kilometer. A rental snapshots these values. At completion, verified pickup and return odometers determine traveled and excess kilometers; valid excess and fuel charges are added to the final bill with an itemized calculation.' },
    { title:'5. Cancellations, changes, and availability', body:'Cancellation, extension, late return, no-show, location-change, and refund rights depend on the confirmed company terms and mandatory law. FleetFlow prevents overlapping bookings and applies an operational turnaround buffer, but a company may substitute, upgrade, cancel, or refund when required by law, safety, breakdown, or genuine unavailability.' },
    { title:'6. Acceptable use', body:'Users must not provide false identity or payment information, bypass availability or access controls, scrape private data, interfere with service, upload malicious content, misuse a vehicle, permit unauthorized drivers, or use FleetFlow or a rented vehicle for unlawful activity.' },
    { title:'7. Incidents and disputes', body:'For accident, theft, breakdown, injury, roadside danger, or official seizure, contact the competent local authority and rental company immediately and follow the contract and insurer instructions. Rental disputes go first to the rental company; platform-function, privacy, and account issues go to FleetFlow Public Support.' },
    { title:'8. Liability and changes', body:'To the extent permitted by mandatory law, FleetFlow is not responsible for a rental company’s vehicle, driving conduct, physical handover, independent terms, or off-platform acts. Nothing excludes liability that cannot lawfully be excluded. We may update platform conditions prospectively; an existing confirmed rental keeps its snapshotted commercial terms.' },
  ],
  ar:[
    { title:'1. دور المنصة', body:'توفر فليت فلو تقنية السوق والحجز والمستندات والتواصل وتشغيل الأسطول. ما لم تُذكر فليت فلو صراحة بوصفها مقدم السيارة في العقد، فإن شركة التأجير ـ لا فليت فلو ـ هي المالكة أو المسيطرة على السيارة والمؤجر المسؤول عن التنفيذ.' },
    { title:'2. الحسابات والصلاحية', body:'يجب تقديم معلومات صحيحة وحماية الوصول للحساب واستخدام الهويات ومساحات الشركات المصرح بها فقط. يؤكد مدير الشركة أن لديه صلاحية نشر السيارات والسياسات والأسعار والمستندات وشروط العقود للنشاط.' },
    { title:'3. الإعلانات وعقود الإيجار', body:'الإعلان ليس عقد إيجار. الشروط الملزمة هي العرض/العقد المؤكد وشروط الشركة المطبقة وملحق السوق والأحكام الآمرة. تتحمل الشركة مسؤولية دقة الإعلان وتوفر السيارة وترخيص النشاط والتأمين والصلاحية الفنية والضرائب والرسوم النظامية.' },
    { title:'4. الأسعار والمسافة والوقود والإضافات', body:'قبل الحجز يشاهد المستأجر الأسعار والعروض والخدمات والحماية والمواقع وشروط الوقود وحد الكيلومترات اليومي ورسم كل كيلومتر زائد. يحفظ الإيجار هذه القيم، وعند الإكمال تحدد قراءات عداد الاستلام والإعادة المؤكدة المسافة والزيادة وتضاف الرسوم الصحيحة والوقود إلى الفاتورة النهائية بتفصيل واضح.' },
    { title:'5. الإلغاء والتغييرات والتوفر', body:'تتحدد حقوق الإلغاء والتمديد والتأخير وعدم الحضور وتغيير الموقع والاسترداد وفق شروط الشركة المؤكدة والأحكام الآمرة. تمنع فليت فلو تداخل الحجوزات وتطبق مهلة تشغيلية، وقد تستبدل الشركة أو ترقي أو تلغي أو ترد المبلغ إذا أوجب النظام أو السلامة أو العطل أو عدم التوفر الحقيقي.' },
    { title:'6. الاستخدام المقبول', body:'يحظر تقديم هوية أو دفع زائف أو تجاوز ضوابط التوفر والوصول أو جمع البيانات الخاصة أو تعطيل الخدمة أو رفع محتوى ضار أو إساءة استخدام السيارة أو تمكين سائق غير مصرح أو استخدام فليت فلو أو السيارة لغرض غير مشروع.' },
    { title:'7. الحوادث والنزاعات', body:'عند حادث أو سرقة أو عطل أو إصابة أو خطر طريق أو حجز رسمي، تواصل فوراً مع الجهة المحلية المختصة وشركة التأجير واتبع العقد وتعليمات المؤمن. تبدأ نزاعات الإيجار مع شركة التأجير، أما مشكلات المنصة والخصوصية والحساب فتوجّه إلى الدعم العام لفليت فلو.' },
    { title:'8. المسؤولية والتغييرات', body:'في الحدود التي يسمح بها النظام الآمر، لا تتحمل فليت فلو مسؤولية سيارة شركة التأجير أو سلوك القيادة أو التسليم الفعلي أو شروط الشركة المستقلة أو التصرفات خارج المنصة. لا يُستبعد ما لا يجوز استبعاده نظاماً. يمكن تحديث شروط المنصة للمستقبل، بينما يحتفظ الإيجار المؤكد بشروطه المالية المحفوظة.' },
  ],
};

export const marketTerms:Record<'ksa'|'yemen',Record<Lang,ContentSection[]>> = {
  ksa:{
    en:[
      { title:'Saudi Arabia — operator and contract requirements', body:'The rental company must hold the licenses and vehicle operating authority required by the Transport General Authority and use any mandatory electronic or unified contract system. The company is responsible for required contract fields, operating cards, authorized branches, and regulatory system integration.' },
      { title:'Saudi Arabia — renter eligibility', body:'The renter and each authorized driver must present valid approved identification and a driving license valid for the entire contract, satisfy the issued insurance policy conditions, and complete any required identity/mobile verification and electronic approval.' },
      { title:'Saudi Arabia — vehicle, insurance, and handover', body:'The company must provide a roadworthy, lawfully registered vehicle with applicable insurance. The contract and handover record should disclose vehicle and policy information, coverage and deductible, odometer, allowed kilometers and excess rate, fuel type/level and return policy, locations, dates, price, and additional services.' },
      { title:'Saudi Arabia — return, incidents, and fees', body:'The renter must return the vehicle at the agreed time, place, condition, fuel level, and odometer process. Different-branch, late, damage, traffic, fuel, and excess-distance charges apply only as stated in the contract and allowed by law. Accidents require the report/instructions of the competent authorities and insurer.' },
      { title:'Saudi Arabia — tax, privacy, and complaints', body:'Prices and tax invoices must handle VAT and other mandatory charges where applicable. Saudi-resident personal data is processed under the Personal Data Protection Law where applicable. Complaints may be raised with the rental company, FleetFlow for platform issues, or the competent Saudi authority.' },
    ],
    ar:[
      { title:'السعودية — متطلبات المنشأة والعقد', body:'يجب أن تحمل شركة التأجير التراخيص وبطاقات التشغيل المطلوبة من الهيئة العامة للنقل وأن تستخدم أي نظام عقد إلكتروني أو موحد إلزامي. تتحمل الشركة مسؤولية حقول العقد المطلوبة والفروع المصرحة والتكامل مع الأنظمة التنظيمية.' },
      { title:'السعودية — أهلية المستأجر', body:'يقدم المستأجر وكل سائق مفوض إثبات هوية معتمداً ورخصة قيادة سارية طوال العقد، ويلتزم بشروط وثيقة التأمين الصادرة، ويكمل أي تحقق مطلوب للهوية أو الجوال والموافقة الإلكترونية.' },
      { title:'السعودية — السيارة والتأمين والتسليم', body:'تقدم الشركة سيارة صالحة ومسجلة نظاماً ومؤمنة بالتغطية المطبقة. ينبغي أن يفصح العقد ومحضر التسليم عن بيانات السيارة والوثيقة والتغطية والتحمل والعداد والكيلومترات المسموحة وسعر الزيادة ونوع/مستوى الوقود وسياسة الإعادة والمواقع والتواريخ والسعر والخدمات.' },
      { title:'السعودية — الإعادة والحوادث والرسوم', body:'يعيد المستأجر السيارة في الوقت والموقع والحالة ومستوى الوقود المتفق عليها ويتبع إجراء العداد. لا تطبق رسوم الفرع المختلف أو التأخير أو الضرر أو المخالفات أو الوقود أو المسافة الزائدة إلا وفق العقد والنظام. تتطلب الحوادث تقرير وتعليمات الجهات المختصة والمؤمن.' },
      { title:'السعودية — الضرائب والخصوصية والشكاوى', body:'تراعي الأسعار والفواتير الضريبة المضافة والرسوم الإلزامية حيث تنطبق. تعالج بيانات المقيمين وفق نظام حماية البيانات الشخصية حيث ينطبق. تقدم الشكوى لشركة التأجير، أو لفليت فلو في مشكلة المنصة، أو للجهة السعودية المختصة.' },
    ],
  },
  yemen:{
    en:[
      { title:'Yemen — operator and documentation', body:'The rental company is responsible for holding the commercial, professional, transport, municipal/local, tax, vehicle, and other approvals required in the governorate where it operates. Each vehicle must have valid registration and any required inspection, insurance, and operating documents.' },
      { title:'Yemen — renter and driver', body:'The renter and every authorized driver must provide reliable identity and a valid driving license accepted by the competent authority and company/insurer. Foreign-license and travel-document requirements must be confirmed with the company and competent authorities before pickup.' },
      { title:'Yemen — contract and pricing', body:'The written or electronic agreement should identify the parties, authorized drivers, vehicle, locations, dates, rate/currency, deposits, taxes/fees, insurance and exclusions, fuel, odometer, daily allowance, excess rate, services, return, damage, accident, extension, cancellation, and dispute terms. Company terms cannot override mandatory law.' },
      { title:'Yemen — road use and incidents', body:'Drivers must follow the applicable Yemeni traffic law, posted signs, right-hand traffic, registration and license requirements, safety directions, checkpoints, and local authority instructions. Accidents, theft, damage, breakdowns, or official detention must be reported promptly to the company and competent authority.' },
      { title:'Yemen — operating environment and disputes', body:'Availability, routes, payment rails, insurance, communications, and authority access may vary by location. A company may restrict pickup, return, or travel areas for safety or legal reasons if disclosed before confirmation. Disputes follow the contract, applicable Yemeni law, and the competent court or authority; FleetFlow handles only platform-related issues.' },
    ],
    ar:[
      { title:'اليمن — المنشأة والوثائق', body:'تتحمل شركة التأجير مسؤولية السجل التجاري وترخيص المهنة والنقل والموافقات البلدية/المحلية والضريبية ووثائق المركبة وغيرها مما يطلب في المحافظة التي تعمل بها. تحمل كل سيارة تسجيلاً وفحصاً وتأميناً ووثائق تشغيل سارية حيث تكون مطلوبة.' },
      { title:'اليمن — المستأجر والسائق', body:'يقدم المستأجر وكل سائق مفوض هوية موثوقة ورخصة قيادة سارية تقبلها الجهة المختصة والشركة/المؤمن. يجب التحقق من متطلبات الرخص الأجنبية ووثائق السفر مع الشركة والسلطات المختصة قبل الاستلام.' },
      { title:'اليمن — العقد والتسعير', body:'ينبغي أن يحدد الاتفاق المكتوب أو الإلكتروني الأطراف والسائقين والسيارة والمواقع والتواريخ والسعر/العملة والتأمينات والضرائب والرسوم والتغطية والاستثناءات والوقود والعداد والحد اليومي وسعر الزيادة والخدمات والإعادة والضرر والحادث والتمديد والإلغاء والنزاع. لا تتجاوز شروط الشركة أحكام القانون الآمرة.' },
      { title:'اليمن — استخدام الطريق والحوادث', body:'يلتزم السائق بقانون المرور اليمني النافذ والإشارات والمرور على الجانب الأيمن ومتطلبات التسجيل والرخصة وإرشادات السلامة ونقاط التفتيش وتعليمات السلطات المحلية. يجب إبلاغ الشركة والجهة المختصة سريعاً عن الحادث أو السرقة أو الضرر أو العطل أو الحجز.' },
      { title:'اليمن — بيئة التشغيل والنزاعات', body:'قد تختلف التوفر والطرق ووسائل الدفع والتأمين والاتصالات والوصول للسلطات حسب الموقع. يجوز للشركة تقييد مناطق الاستلام أو الإعادة أو السفر لأسباب سلامة أو نظامية إذا أفصحت قبل التأكيد. تخضع النزاعات للعقد والقانون اليمني والمحكمة أو الجهة المختصة؛ وتعالج فليت فلو مشكلات المنصة فقط.' },
    ],
  },
};
