'use client';
import { CreditCard, Landmark, Plus, Save, ShieldCheck } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/client-api';
import { money, shortDate } from '@/lib/format';
import { useI18n } from '@/lib/i18n';
import { Modal, Skeleton, StatusBadge, useToast } from '@/components/ui';

const blankAccount={code:'KURAIMI_SAR',accountNumber:'',accountHolder:'FleetFlow',instructions:'',active:true};
export default function PaymentsPage(){
  const{t}=useI18n();const toast=useToast();const[banks,setBanks]=useState<any[]|null>(null);const[gateway,setGateway]=useState<any>(null);const[payments,setPayments]=useState<any[]|null>(null);const[saving,setSaving]=useState('');const[addOpen,setAddOpen]=useState(false);const[addForm,setAddForm]=useState<any>(blankAccount);
  useEffect(()=>{Promise.all([api('/admin/bank-accounts'),api('/admin/payment-settings'),api('/admin/payments')]).then(([b,g,p]:any[])=>{setBanks(b.accounts);setGateway(g.settings);setPayments(p.payments)}).catch((error:any)=>toast(error.message,true))},[]);
  const configuredBanks=useMemo(()=>banks?.filter(bank=>bank.accountNumber)||[],[banks]);
  const availableBanks=useMemo(()=>banks?.filter(bank=>!bank.accountNumber)||[],[banks]);
  const updateBank=(id:number,changes:any)=>setBanks(current=>current?.map(item=>item.id===id?{...item,...changes}:item)||current);
  const saveBank=async(bank:any)=>{setSaving(`bank-${bank.id}`);try{const result:any=await api('/admin/bank-accounts',{method:'PATCH',body:JSON.stringify(bank)});updateBank(bank.id,result.account);toast(t('bankAccountSaved'))}catch(error:any){toast(error.message,true)}finally{setSaving('')}};
  const openAdd=()=>{if(!availableBanks.length){toast(t('allBankChannelsConfigured'));return}setAddForm({...blankAccount,code:availableBanks[0].code});setAddOpen(true)};
  const addBank=async(event:FormEvent)=>{event.preventDefault();setSaving('add-bank');try{const result:any=await api('/admin/bank-accounts',{method:'POST',body:JSON.stringify(addForm)});updateBank(result.account.id,result.account);setAddOpen(false);toast(t('bankAccountAdded'))}catch(error:any){toast(error.message,true)}finally{setSaving('')}};
  const saveGateway=async()=>{setSaving('gateway');try{const result:any=await api('/admin/payment-settings',{method:'PATCH',body:JSON.stringify(gateway)});setGateway(result.settings);toast(t('paymentSettingsSaved'))}catch(error:any){toast(error.message,true)}finally{setSaving('')}};
  if(!banks||!gateway||!payments)return <><Skeleton cards={4}/><Skeleton rows={5}/></>;
  return <div className="platform-admin-page admin-tab-page">
    <section className="admin-section bank-management-section"><header><div><span><Landmark/></span><div><h3>{t('platformBankAccounts')}</h3><p>{t('platformBankAccountsText')}</p></div></div><button className="btn primary" type="button" onClick={openAdd} disabled={!availableBanks.length}><Plus/>{t('addBankAccount')}</button></header>{configuredBanks.length?<div className="admin-bank-grid">{configuredBanks.map(bank=><article key={bank.id}><header><div><CreditCard/><span><strong>{bank.label}</strong><small>{bank.currency} · {bank.code}</small></span></div><label><input type="checkbox" checked={bank.active} onChange={event=>updateBank(bank.id,{active:event.target.checked})}/>{t('visible')}</label></header><label>{t('accountNumber')}<input dir="ltr" value={bank.accountNumber} onChange={event=>updateBank(bank.id,{accountNumber:event.target.value})}/></label><label>{t('accountHolder')}<input value={bank.accountHolder} onChange={event=>updateBank(bank.id,{accountHolder:event.target.value})}/></label><label>{t('transferInstructions')}<textarea value={bank.instructions} onChange={event=>updateBank(bank.id,{instructions:event.target.value})}/></label><button className="btn secondary" onClick={()=>saveBank(bank)} disabled={saving===`bank-${bank.id}`}><Save/>{t('saveBankAccount')}</button></article>)}</div>:<div className="bank-account-empty"><Landmark/><strong>{t('noBankAccountsConfigured')}</strong><p>{t('noBankAccountsConfiguredText')}</p><button className="btn primary" type="button" onClick={openAdd}><Plus/>{t('addBankAccount')}</button></div>}<div className="bank-channel-summary"><span>{configuredBanks.length} {t('configured')}</span><span>{availableBanks.length} {t('availableChannels')}</span></div></section>
    <section className="admin-section gateway-section"><header><div><span><CreditCard/></span><div><h3>{t('kuraimiAutomaticPayment')}</h3><p>{t('kuraimiAutomaticPaymentText')}</p></div></div><em className={gateway.apiKeyConfigured?'configured':'missing'}>{gateway.apiKeyConfigured?t('apiKeyConfigured'):t('apiKeyMissing')}</em></header><div className="gateway-form"><label>{t('apiBaseUrl')}<input dir="ltr" value={gateway.apiBaseUrl} onChange={event=>setGateway({...gateway,apiBaseUrl:event.target.value})} placeholder="https://api.kuraimibank.com"/></label><label>{t('merchantId')}<input dir="ltr" value={gateway.merchantId} onChange={event=>setGateway({...gateway,merchantId:event.target.value})}/></label><label>{t('paymentCreatePath')}<input dir="ltr" value={gateway.createPaymentPath} onChange={event=>setGateway({...gateway,createPaymentPath:event.target.value})}/></label><label className="gateway-enable"><input type="checkbox" checked={gateway.enabled} onChange={event=>setGateway({...gateway,enabled:event.target.checked})}/><span><strong>{t('enableAutomaticPayments')}</strong><small>{t('enableAutomaticPaymentsHint')}</small></span></label></div><div className="gateway-security-note"><ShieldCheck/><p>{t('apiKeySecurityText')}</p></div><button className="btn primary" onClick={saveGateway} disabled={saving==='gateway'}><Save/>{t('savePaymentSettings')}</button></section>
    <section className="panel payment-records"><header><div><h3>{t('subscriptionPayments')}</h3><p>{t('subscriptionPaymentsText')}</p></div><span>{payments.length}</span></header><div className="responsive-table"><table><thead><tr><th>{t('companyRole')}</th><th>{t('subscriptionPackage')}</th><th>{t('paymentReference')}</th><th>{t('amount')}</th><th>{t('status')}</th><th>{t('issued')}</th></tr></thead><tbody>{payments.length?payments.map(payment=><tr key={payment.id}><td><strong>{payment.companyName}</strong></td><td>{payment.planName}</td><td dir="ltr">{payment.providerReference||payment.internalReference}</td><td>{money(payment.amount)} {payment.currency}</td><td><StatusBadge status={payment.status}/></td><td>{shortDate(payment.createdAt)}</td></tr>):<tr><td colSpan={6}>{t('noSubscriptionPayments')}</td></tr>}</tbody></table></div></section>
    <Modal open={addOpen} onClose={()=>setAddOpen(false)} title={t('addBankAccount')} subtitle={t('addBankAccountText')}><form className="bank-add-form" onSubmit={addBank}><label>{t('bankAccountChannel')}<select value={addForm.code} onChange={event=>setAddForm({...addForm,code:event.target.value})}>{availableBanks.map(bank=><option value={bank.code} key={bank.code}>{bank.label} · {bank.currency}</option>)}</select></label><label>{t('accountNumber')}<input dir="ltr" autoFocus value={addForm.accountNumber} onChange={event=>setAddForm({...addForm,accountNumber:event.target.value})} placeholder={t('accountNumberPlaceholder')} required/></label><label>{t('accountHolder')}<input value={addForm.accountHolder} onChange={event=>setAddForm({...addForm,accountHolder:event.target.value})} required/></label><label>{t('transferInstructions')}<textarea value={addForm.instructions} onChange={event=>setAddForm({...addForm,instructions:event.target.value})} placeholder={t('transferInstructionsPlaceholder')}/></label><label className="bank-add-visible"><input type="checkbox" checked={addForm.active} onChange={event=>setAddForm({...addForm,active:event.target.checked})}/><span><strong>{t('publishImmediately')}</strong><small>{t('publishImmediatelyText')}</small></span></label><footer><button type="button" className="btn secondary" onClick={()=>setAddOpen(false)}>{t('cancel')}</button><button className="btn primary" disabled={saving==='add-bank'}><Plus/>{saving==='add-bank'?t('saving'):t('addBankAccount')}</button></footer></form></Modal>
  </div>;
}
