import { and, eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { promotionVehicles, promotions } from '@/db/schema';
import { requireUser } from '@/lib/auth';
import { fail, ok } from '@/lib/http';
import { promotionState } from '@/lib/pricing';

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser('company');const{id}=await params;const db=await getDb();const[existing]=await db.select().from(promotions).where(and(eq(promotions.id,Number(id)),eq(promotions.companyId,user.companyId!))).limit(1);if(!existing)return ok({error:'Promotion not found'},404);const body=await request.json();const data:any={};for(const key of ['name','type','appliesTo','enabled'])if(body[key]!==undefined)data[key]=body[key];if(body.code!==undefined)data.code=body.code.toUpperCase();for(const key of ['value','minQuantity'])if(body[key]!==undefined)data[key]=Number(body[key]);for(const key of ['startsAt','endsAt'])if(body[key]!==undefined)data[key]=new Date(body[key]);const[row]=await db.update(promotions).set(data).where(eq(promotions.id,existing.id)).returning();let vehicleIds:number[]=[];if(body.vehicleIds!==undefined){await db.delete(promotionVehicles).where(eq(promotionVehicles.promotionId,row.id));vehicleIds=body.vehicleIds;if(row.appliesTo==='selected'&&vehicleIds.length)await db.insert(promotionVehicles).values(vehicleIds.map(vehicleId=>({promotionId:row.id,vehicleId})))}else{vehicleIds=(await db.select().from(promotionVehicles).where(eq(promotionVehicles.promotionId,row.id))).map((x:any)=>x.vehicleId)}return ok({promotion:{...row,state:promotionState(row),vehicleIds}})}catch(error){return fail(error)}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser('company');const{id}=await params;const db=await getDb();await db.delete(promotions).where(and(eq(promotions.id,Number(id)),eq(promotions.companyId,user.companyId!)));return ok({ok:true})}catch(error){return fail(error)}}
