'use client';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, CarFront, CircleDollarSign, Fuel, Gauge, History, MapPin, Pencil, Star, UserRound } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { api } from '@/lib/client-api';
import { money, shortDate } from '@/lib/format';
import { useI18n } from '@/lib/i18n';
import { Avatar, Empty, Skeleton, StatusBadge } from '@/components/ui';

export default function VehicleDetail(){const{t}=useI18n();const{id}=useParams();const[data,setData]=useState<any>(null);useEffect(()=>{api(`/vehicles/${id}`).then(setData)},[id]);if(!data)return <Skeleton rows={6}/>;const v=data.vehicle;return <><div className="detail-header"><Link href="/dashboard/vehicles" className="back-link"><ArrowLeft/>{t('fleet')}</Link><div><span className="eyebrow">{v.licensePlate}</span><h2>{v.make} {v.model}</h2><p>{v.year} · {t(v.category)} · {v.companyName}</p></div><div><StatusBadge status={v.status}/><Link href="/dashboard/vehicles" className="btn secondary"><Pencil/>{t('edit')}</Link></div></div><div className="detail-grid"><section className="panel vehicle-hero-panel"><img src={v.image}/><div className="detail-specs">{[[Gauge,`${v.odometer.toLocaleString()} ${t('miles')}`],[Fuel,t(v.fuel)],[UserRound,`${v.seats} ${t('seats')}`],[MapPin,v.location]].map(([Icon,value]:any)=><div key={value}><Icon/><span>{value}</span></div>)}</div><div className="features-list">{v.features.map((x:string)=><span key={x}>{t(x)}</span>)}</div></section><aside className="detail-side"><div className="detail-metrics"><article><span><CircleDollarSign/></span><div><small>{t('lifetimeRevenue')}</small><strong>{money(data.analytics.revenue)}</strong></div></article><article><span><History/></span><div><small>{t('completedTrips')}</small><strong>{data.analytics.trips}</strong></div></article><article><span><CalendarDays/></span><div><small>{t('currentBookings')}</small><strong>{data.analytics.active}</strong></div></article></div><section className="panel pricing-panel"><h3>{t('pricing')}</h3>{[['hour',v.hourlyRate],['day',v.dailyRate],['week',v.weeklyRate],['month',v.monthlyRate]].map(([label,value])=><div key={label}><span>{t(label as string)}</span><strong>{money(value as number)}</strong></div>)}</section></aside></div><section className="panel history-panel"><header><div><h3>{t('rentalHistory')}</h3><p>{t('completeVehicleRecord')}</p></div><History/></header>{data.history.length===0?<Empty icon={CarFront} title={t('noRentals')} text={t('noRentalsText')}/>:<div className="responsive-table"><table><thead><tr><th>{t('customer')}</th><th>{t('dates')}</th><th>{t('duration')}</th><th>{t('discount')}</th><th>{t('total')}</th><th>{t('status')}</th></tr></thead><tbody>{data.history.map((r:any)=><tr key={r.id}><td><div className="table-person"><Avatar name={r.customer} initials={r.avatar} size="sm"/><span><strong>{r.customer}</strong><small>{r.customerEmail}</small></span></div></td><td>{shortDate(r.startsAt)} – {shortDate(r.endsAt)}</td><td>{r.quantity} {t(r.rateType)}</td><td>{r.discount?`−${money(r.discount)}`:'—'}</td><td><strong>{money(r.total)}</strong></td><td><StatusBadge status={r.status}/></td></tr>)}</tbody></table></div>}</section></>}
