'use client';
import { BarChart3, Building2, CalendarDays, CarFront, Download, FileSpreadsheet, Fuel, Gauge, LoaderCircle, Printer, UsersRound, Wrench } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Skeleton, useToast } from '@/components/ui';
import { api, apiFile } from '@/lib/client-api';
import { formatMoney, shortDate } from '@/lib/format';
import { useI18n } from '@/lib/i18n';

const today=new Date().toISOString().slice(0,10);
const yearStart=`${new Date().getFullYear()}-01-01`;
const pct=(value:number)=>`${Number(value||0).toFixed(1)}%`;
const num=(value:number)=>Number(value||0).toLocaleString();
let reportCurrency='USD';
const money=(value:number)=>formatMoney(Number(value)||0, reportCurrency);
const chunks=<T,>(rows:T[],size:number)=>Array.from({length:Math.ceil(rows.length/size)},(_,index)=>rows.slice(index*size,index*size+size));

export default function ReportsPage(){
  const{t}=useI18n();const toast=useToast();
  const[filters,setFilters]=useState({type:'company',start:yearStart,end:today,vehicleId:'',customerId:''});
  const[report,setReport]=useState<any>(null);const[loading,setLoading]=useState(true);const[exporting,setExporting]=useState('');
  const renterMode=report?.mode==='renter';
  reportCurrency=report?.currency||'USD';
  const query=useMemo(()=>{const params=new URLSearchParams({start:filters.start,end:filters.end});if(!renterMode){params.set('type',filters.type);if(filters.vehicleId)params.set('vehicleId',filters.vehicleId);if(filters.customerId)params.set('customerId',filters.customerId)}return params.toString()},[filters,renterMode]);
  const generate=async(nextQuery=query)=>{setLoading(true);try{const data:any=await api(`/reports?${nextQuery}`);setReport(data.report)}catch(error:any){toast(error.message,true)}finally{setLoading(false)}};
  useEffect(()=>{generate()},[]);
  const set=(key:string,value:string)=>setFilters(current=>({...current,[key]:value}));
  const setPeriod=(key:'start'|'end',value:string)=>{const next={...filters,[key]:value};setFilters(next);if(renterMode&&next.start&&next.end){const params=new URLSearchParams({start:next.start,end:next.end});generate(params.toString())}};
  const changeType=(type:string)=>{const next={...filters,type};if(type==='vehicle'&&!next.vehicleId&&report?.options.vehicles[0])next.vehicleId=String(report.options.vehicles[0].id);if(type==='customer'&&!next.customerId&&report?.options.customers[0])next.customerId=String(report.options.customers[0].id);setFilters(next)};
  const download=async(format:'pdf'|'excel')=>{setExporting(format);try{const blob=await apiFile(`/reports/export?${query}&format=${format}`);const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${report?.reportNumber||'FleetFlow-report'}.${format==='pdf'?'pdf':'xls'}`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(t(format==='pdf'?'reportPdfReady':'reportExcelReady'))}catch(error:any){toast(error.message,true)}finally{setExporting('')}};
  if(loading&&!report)return <><div className="page-heading"><div><span className="eyebrow"><BarChart3/>{t('reportingAnalytics')}</span><h2>{t('reports')}</h2></div></div><Skeleton rows={8}/></>;
  const companyMode=report?.mode!=='renter';
  return <><div className="page-heading"><div><span className="eyebrow"><BarChart3/>{t('reportingAnalytics')}</span><h2>{t(companyMode?'reports':'personalRentalReport')}</h2><p>{t(companyMode?'reportsPageText':'personalReportsPageText')}</p></div></div>
    <section className={`report-filter-panel ${companyMode?'':'personal-report-controls'}`}><header><BarChart3/><div><h3>{t(companyMode?'reportFilters':'personalDashboardPeriod')}</h3><p>{t(companyMode?'reportFiltersText':'personalDashboardPeriodText')}</p></div></header>{companyMode?<div className="report-filter-grid"><label>{t('company')}<input value={report?.owner.name||''} readOnly /></label><label>{t('reportType')}<select value={filters.type} onChange={event=>changeType(event.target.value)}><option value="company">{t('companyPerformanceReport')}</option><option value="rental_history">{t('detailedRentalHistory')}</option><option value="vehicle">{t('vehicleDetailedReport')}</option><option value="customer">{t('customerRentalReport')}</option></select></label><label>{t('periodFrom')}<input type="date" value={filters.start} max={filters.end} onChange={event=>set('start',event.target.value)}/></label><label>{t('periodTo')}<input type="date" value={filters.end} min={filters.start} onChange={event=>set('end',event.target.value)}/></label><label>{t('vehicle')}<select value={filters.vehicleId} onChange={event=>set('vehicleId',event.target.value)}><option value="">{t('allVehicles')}</option>{report?.options.vehicles.map((vehicle:any)=><option value={vehicle.id} key={vehicle.id}>{vehicle.label} · {vehicle.licensePlate}</option>)}</select></label><label>{t('customer')}<select value={filters.customerId} onChange={event=>set('customerId',event.target.value)}><option value="">{t('allCustomers')}</option>{report?.options.customers.map((customer:any)=><option value={customer.id} key={customer.id}>{customer.name} · {customer.email}</option>)}</select></label></div>:<div className="report-filter-grid personal-report-period"><label>{t('periodFrom')}<input type="date" value={filters.start} max={filters.end} onChange={event=>setPeriod('start',event.target.value)}/></label><label>{t('periodTo')}<input type="date" value={filters.end} min={filters.start} onChange={event=>setPeriod('end',event.target.value)}/></label></div>}<footer>{companyMode&&<button className="btn primary" onClick={()=>generate()} disabled={loading}>{loading?<LoaderCircle className="spin"/>:<BarChart3/>}{t('generateReport')}</button>}<button className="btn secondary" onClick={()=>download('pdf')} disabled={!report||!!exporting||loading}>{exporting==='pdf'?<LoaderCircle className="spin"/>:<Download/>}{t('exportPdf')}</button>{companyMode&&<button className="btn secondary" onClick={()=>download('excel')} disabled={!report||!!exporting}>{exporting==='excel'?<LoaderCircle className="spin"/>:<FileSpreadsheet/>}{t('exportExcel')}</button>}<button className="btn secondary" onClick={()=>window.print()} disabled={!report||loading}><Printer/>{t('printPreview')}</button></footer></section>
    {loading&&!report?<Skeleton rows={8}/>:report&&<ReportPreview report={report}/>}</>;
}

function ReportPreview({report}:{report:any}){const{t}=useI18n();if(report.mode==='renter')return <PersonalDashboardPreview report={report}/>;const rentalPages=chunks(report.rentals,12),maintenancePages=chunks(report.maintenance,12),fuelPages=chunks(report.fueling,12),odoPages=chunks(report.odometer,14);const pages:any[]=[];
  pages.push(<ReportSheet report={report} key="summary"><Executive report={report}/>{report.reportType==='vehicle'&&report.vehicleDetail&&<VehicleIdentity report={report}/>}</ReportSheet>);
  chunks(report.monthly,12).forEach((rows,index)=>pages.push(<ReportSheet report={report} key={`monthly-${index}`} section={t('rentalPerformance')}><Monthly report={report} rows={rows}/></ReportSheet>));
  if(report.reportType==='company')pages.push(<ReportSheet report={report} key="profitability" section={t('vehicleProfitability')}><VehicleProfitability report={report}/><CustomerPerformance report={report}/></ReportSheet>);
  rentalPages.forEach((rows,index)=>pages.push(<ReportSheet report={report} key={`rentals-${index}`} section={t('detailedRentalHistory')}><RentalTable rows={rows}/>{index===rentalPages.length-1&&<RentalTotals report={report}/>}</ReportSheet>));
  if(report.mode==='company'&&(report.reportType==='company'||report.reportType==='vehicle')){maintenancePages.forEach((rows,index)=>pages.push(<ReportSheet report={report} key={`maintenance-${index}`} section={t('maintenanceHistory')}><MaintenanceTable rows={rows}/></ReportSheet>));fuelPages.forEach((rows,index)=>pages.push(<ReportSheet report={report} key={`fuel-${index}`} section={t('fuelingHistory')}><FuelTable rows={rows}/></ReportSheet>));if(report.reportType==='vehicle')odoPages.forEach((rows,index)=>pages.push(<ReportSheet report={report} key={`odo-${index}`} section={t('odometerUsageHistory')}><OdometerTable rows={rows}/></ReportSheet>));}
  return <section className="report-preview"><header><div><strong>{t('reportPreview')}</strong><span>{pages.length} {t('pages')}</span></div><small>{t('a4LandscapePreview')}</small></header><div className="report-preview-scroll"><div className="report-page-stack">{pages.map((page,index)=><div className="report-page-wrap" key={index}>{page}<span className="report-screen-page-number">{t('page')} {index+1} / {pages.length}</span></div>)}</div></div></section>;
}
function PersonalDashboardPreview({report}:{report:any}){const{t}=useI18n();return <section className="report-preview personal-dashboard-preview"><header><div><strong>{t('personalRentalReport')}</strong><span>{t('singleDashboard')}</span></div><small>{t('a4PersonalDashboard')}</small></header><div className="report-preview-scroll"><div className="report-page-stack"><div className="report-page-wrap"><ReportSheet report={report}><PersonalDashboard report={report}/></ReportSheet></div></div></div></section>}
function PersonalDashboard({report}:{report:any}){const{t}=useI18n();const s=report.summary;const statuses=['pending','active','completed','cancelled'];const recent=report.rentals.slice(-6).reverse();const monthly=report.monthly.slice(-6);return <><ReportSectionTitle icon={BarChart3} title={t('personalRentalOverview')}/><div className="report-kpis personal-report-kpis"><div><span>{t('totalRentals')}</span><strong>{num(s.totalRentals)}</strong></div><div><span>{t('completedTripsLabel')}</span><strong>{num(s.completedRentals)}</strong></div><div><span>{t('totalSpent')}</span><strong>{money(s.totalSpent)}</strong></div><div><span>{t('totalDistance')}</span><strong>{num(s.totalDistance)} km</strong></div></div><div className="personal-dashboard-grid"><section className="personal-status-card"><ReportSectionTitle icon={Gauge} title={t('rentalStatusOverview')}/><div>{statuses.map(status=><span key={status}><small>{t(status)}</small><strong>{report.rentals.filter((row:any)=>row.status===status).length}</strong></span>)}</div><footer><span>{t('totalRentalDays')}</span><strong>{num(s.rentalDays)} {t('rentalDays')}</strong></footer></section><section><ReportSectionTitle icon={CalendarDays} title={t('monthlyRentalActivity')}/><ReportTable headers={[t('month'),t('rentals'),t('totalSpent')]} rows={monthly.map((row:any)=>[shortDate(row.monthStart),row.rentals,money(row.spent)])}/></section></div><section className="personal-recent-rentals"><ReportSectionTitle icon={CarFront} title={t('recentRentalActivity')}/><ReportTable headers={[t('contract'),t('vehicle'),t('status'),t('startDate'),t('endDate'),t('days'),t('rentalAmount')]} rows={recent.map((row:any)=>[row.contract,`${row.make} ${row.model} · ${row.licensePlate}`,t(row.status),shortDate(row.startsAt),shortDate(row.endsAt),row.days,money(row.total)])}/></section></>}
function ReportSheet({report,section,children}:{report:any;section?:string;children:any}){const{t}=useI18n();return <article className={`report-sheet ${report.mode==='renter'?'personal-report-sheet':''}`}><header><div className="report-company-logo"><span>{report.owner.logo}</span><div><strong>{t('brand')}</strong><small>{t('fleetManagementSystem')}</small></div></div><div className="report-sheet-title"><small>{section||t(report.mode==='renter'?'personalRentalReport':report.reportType==='vehicle'?'vehicleDetailedReport':report.reportType==='rental_history'?'detailedRentalHistory':report.reportType==='customer'?'customerRentalReport':'companyPerformanceReport')}</small><strong>{report.owner.name}</strong><span>{t('reportingPeriod')}: {shortDate(report.period.start)} — {shortDate(report.period.end)}</span></div><div className="report-id"><small>{t('reportNumber')}</small><strong>{report.reportNumber}</strong><span>{t('generated')}: {shortDate(report.generatedAt)}</span></div></header><main>{children}</main><footer><span>{t('fleetManagementSystem')}</span><span>{report.mode==='renter'?t('personalAccount'):report.appliedFilters.vehicle||report.appliedFilters.customer||t('wholeCompany')}</span></footer></article>}
function Executive({report}:{report:any}){const{t}=useI18n();const s=report.summary;const cards=[[t('totalRentals'),num(s.totalRentals),s.changes.rentals],[t('rentalRevenue'),money(s.rentalRevenue),s.changes.revenue],[t('totalCost'),money(s.totalCost),s.changes.cost],[t('netProfit'),money(s.netProfit),s.changes.profit],[t('activeVehicles'),num(s.activeVehicles),null],[t('maintenance'),money(s.maintenanceCost),null],[t('fuelCost'),money(s.fuelCost),null],[t('profitMargin'),pct(s.profitMargin),null]];return <><ReportSectionTitle icon={BarChart3} title={t('executiveSummary')}/><div className="report-kpis">{cards.map(([label,value,trend]:any)=><div key={label}><span>{label}</span><strong>{value}</strong>{trend!=null&&<small className={trend>=0?'positive':'negative'}>{trend>=0?'↑':'↓'} {Math.abs(trend)}%</small>}</div>)}</div><div className="report-financial"><section><ReportSectionTitle icon={Building2} title={t('financialSummary')}/>{[[t('rentalRevenue'),s.rentalRevenue],[t('maintenanceCosts'),-s.maintenanceCost],[t('fuelCosts'),-s.fuelCost],[t('otherVehicleCosts'),-s.otherCost],[t('totalCosts'),-s.totalCost],[t('netProfit'),s.netProfit]].map(([label,value],index)=><div className={index>=4?'total':''} key={label as string}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</section><section className="report-usage-card"><Gauge/><span>{t('fleetUsage')}</span><strong>{num(s.totalDistance)} km</strong><small>{s.rentalDays} {t('rentalDays')} · {s.customerCount} {t('customers')} · {num(s.measuredFuelDistance)} km {t('measuredDistance')} · {money(s.fuelCostPerKm)}/km</small></section></div></>}
function Monthly({report,rows=report.monthly}:{report:any;rows?:any[]}){const{t}=useI18n();return <section><ReportSectionTitle icon={CalendarDays} title={t('rentalPerformance')}/><ReportTable headers={[t('month'),t('rentals'),t('revenue'),t('cost'),t('profit'),t('margin')]} rows={rows.map((row:any)=>[shortDate(row.monthStart),row.rentals,money(row.revenue),money(row.cost),money(row.profit),pct(row.margin)])}/></section>}
function VehicleProfitability({report}:{report:any}){const{t}=useI18n();return <section><ReportSectionTitle icon={CarFront} title={t('vehicleProfitability')}/><ReportTable headers={[t('vehicle'),t('plate'),t('rentals'),t('revenue'),t('maintenance'),t('fuel'),t('fuelCostPerKm'),t('efficiencyRecommendation'),t('profit')]} rows={report.vehicles.slice(0,8).map((row:any)=>[`${row.make} ${row.model}`,row.licensePlate,row.totalRentals,money(row.rentalRevenue),money(row.maintenanceCost),money(row.fuelCost),`${money(row.fuelEfficiency?.costPerKm||0)}/km`,t(`efficiency_${row.fuelEfficiency?.status||'insufficient_data'}`),money(row.netProfit)])}/></section>}
function CustomerPerformance({report}:{report:any}){const{t}=useI18n();return <section><ReportSectionTitle icon={UsersRound} title={t('customerPerformance')}/><ReportTable headers={[t('customer'),t('rentals'),t('rentalDays'),t('distance'),t('revenue')]} rows={report.customers.slice(0,7).map((row:any)=>[row.name,row.rentals,row.rentalDays,`${num(row.distance)} km`,money(row.revenue)])}/></section>}
function VehicleIdentity({report}:{report:any}){const{t}=useI18n();const v=report.vehicleDetail;return <section className="report-vehicle-identity"><div><CarFront/><span><small>{t('vehicle')}</small><strong>{v.make} {v.model} — {v.licensePlate}</strong></span></div><div><span>{t('vin')}</span><strong>{v.vin||'—'}</strong></div><div><span>{t('currentOdometer')}</span><strong>{num(v.odometer)} km</strong></div><div><span>{t('reportingPeriod')}</span><strong>{shortDate(report.period.start)} — {shortDate(report.period.end)}</strong></div></section>}
function RentalTable({rows}:{rows:any[]}){const{t}=useI18n();return <ReportTable headers={[t('contract'),t('vehicle'),t('customer'),t('startDate'),t('endDate'),t('days'),t('startOdometer'),t('endOdometer'),t('distance'),t('rentalAmount')]} rows={rows.map(row=>[row.contract,`${row.make} ${row.model} · ${row.licensePlate}`,row.customer,shortDate(row.startsAt),shortDate(row.endsAt),row.days,row.pickupOdometer??'—',row.returnOdometer??'—',`${num(row.distance)} km`,money(row.total)])}/>}
function RentalTotals({report}:{report:any}){const{t}=useI18n();const s=report.summary;return <div className="report-totals"><span>{t('totalContracts')}: <strong>{s.totalRentals}</strong></span><span>{t('totalRentalDays')}: <strong>{s.rentalDays}</strong></span><span>{t('totalDistance')}: <strong>{num(s.totalDistance)} km</strong></span><span>{t('totalRentalRevenue')}: <strong>{money(s.rentalRevenue)}</strong></span></div>}
function MaintenanceTable({rows}:{rows:any[]}){const{t}=useI18n();return <ReportTable headers={[t('vehicle'),t('serviceDate'),t('type'),t('description'),t('odometer'),t('vendor'),t('status'),t('cost')]} rows={rows.map(row=>[`${row.make} ${row.model} · ${row.licensePlate}`,shortDate(row.serviceDate),t(`maintenancePriority_${row.priority}`),row.title,row.completedOdometer??row.dueOdometer??'—',row.vendor||'—',t(`maintenanceStatus_${row.status}`),money(row.cost)])}/>}
function FuelTable({rows}:{rows:any[]}){const{t}=useI18n();return <ReportTable headers={[t('vehicle'),t('date'),t('odometer'),t('liters'),t('total'),t('distance'),t('fuelCostPerKm'),t('fuelConsumption'),t('employee')]} rows={rows.map(row=>[`${row.make} ${row.model} · ${row.licensePlate}`,shortDate(row.createdAt),row.odometer,num(row.liters),money(row.cost),`${num(row.distanceSincePreviousFuel)} km`,`${money(row.costPerKm)}/km`,row.litersPer100Km?`${num(row.litersPer100Km)} L/100km`:'—',row.employee||'—'])}/>}
function OdometerTable({rows}:{rows:any[]}){const{t}=useI18n();return <ReportTable headers={[t('date'),t('conditionEvent'),t('odometer'),t('fuelLevel'),t('contract'),t('employee'),t('notes')]} rows={rows.map(row=>[shortDate(row.createdAt),t(`condition_${row.eventType}`),`${num(row.odometer)} km`,`${row.fuelLevel}%`,row.rentalId?`R-${String(row.rentalId).padStart(6,'0')}`:'—',row.employee||'—',row.notes||'—'])}/>}
function ReportSectionTitle({icon:Icon,title}:{icon:any;title:string}){return <h3 className="report-section-title"><Icon/>{title}</h3>}
function ReportTable({headers,rows}:{headers:string[];rows:any[][]}){return <div className="report-table"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length}>—</td></tr>}</tbody></table></div>}
