'use client';
import Link from 'next/link';
import { ArrowRight, CalendarCheck, CarFront, Check, ChevronRight, Clock3, Menu, Percent, Search, ShieldCheck, Sparkles, Star, X, Zap } from 'lucide-react';
import { useEffect, useState } from 'react';
import { LanguageToggle, ThemeToggle } from '@/components/theme-controls';
import { Skeleton } from '@/components/ui';
import { useI18n } from '@/lib/i18n';
import { api } from '@/lib/client-api';
import { money } from '@/lib/format';

export default function Landing(){const{t}=useI18n();const[data,setData]=useState<any>(null);const[menu,setMenu]=useState(false);useEffect(()=>{api('/landing').then(setData)},[]);return <div className="landing">
<header className="landing-nav"><Link href="/" className="logo"><span><CarFront/></span>FleetFlow</Link><nav className={menu?'open':''}><Link href="/dashboard/browse">{t('marketplace')}</Link><a href="#deals">{t('deals')}</a><a href="#features">{t('features')}</a></nav><div className="nav-actions"><LanguageToggle/><ThemeToggle/><Link className="btn ghost hide-mobile" href="/login">{t('signIn')}</Link><Link className="btn primary hide-mobile" href="/register">{t('getStarted')}<ArrowRight/></Link><button className="nav-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main><section className="hero"><div className="hero-glow one"/><div className="hero-glow two"/><div className="hero-copy"><span className="eyebrow"><Sparkles/> {t('heroEyebrow')}</span><h1>{t('heroTitle')}</h1><p>{t('heroText')}</p><div className="hero-actions"><Link className="btn primary big" href="/login?role=renter">{t('browseCars')}<ArrowRight/></Link><Link className="btn glass big" href="/login?role=company">{t('listFleet')}<ChevronRight/></Link></div><div className="hero-trust"><span><Check/>No hidden fees</span><span><Check/>Verified partners</span><span><Check/>Instant booking</span></div></div><div className="hero-showcase"><div className="hero-card"><div className="hero-card-top"><span>San Francisco, CA</span><span className="live-dot">Live</span></div><img src="/cars/mercedes.jpg" alt="Mercedes-Benz C-Class"/><div className="floating-chip discount"><Percent/>Save 20%</div><div className="floating-chip rating"><Star fill="currentColor"/>4.9</div><div className="hero-car-info"><div><span>Luxury sedan</span><h3>Mercedes-Benz C-Class</h3><small>CityDrive Rentals</small></div><div><strong>$139</strong><small>/ day</small></div></div></div></div></section>
<section className="landing-stats">{[[data?.stats.vehicles||17,t('liveVehicles')],[data?.stats.companies||3,t('trustedCompanies')],[data?.stats.trips||1248,t('completedTrips')]].map(([value,label],i)=><div key={i}><strong>{value}{i===2?'+':''}</strong><span>{label}</span></div>)}<div className="stat-rating"><span>★★★★★</span><small>4.9 average rating</small></div></section>
<section className="landing-section" id="deals"><div className="section-title"><div><span className="eyebrow">{t('marketplace')}</span><h2>{t('featured')}</h2><p>{t('featuredText')}</p></div><Link href="/login?role=renter">{t('viewAll')}<ArrowRight/></Link></div>{!data?<Skeleton cards={3}/>:<div className="landing-cars">{data.featured.slice(0,3).map((car:any)=><article className="market-card" key={car.id}><div className="market-image"><img src={car.image} alt={`${car.make} ${car.model}`}/>{car.promotion&&<span className="deal-badge"><Zap/> {car.promotion.type==='percentage'?`${car.promotion.value}% off`:`${money(car.promotion.value)} off`}</span>}<span className="rating-badge"><Star fill="currentColor"/>{car.rating}</span></div><div className="market-body"><div className="market-company">{car.companyName}</div><h3>{car.make} {car.model}</h3><div className="market-specs"><span>{car.category}</span><i/> <span>{car.fuel}</span><i/><span>{car.seats} {t('seats')}</span></div><div className="market-price"><span>{t('from')} <strong>{money(car.dailyRate)}</strong> / {t('day')}</span><Link href={`/login?role=renter`}><ArrowRight/></Link></div></div></article>)}</div>}</section>
<section className="feature-section" id="features"><div className="feature-intro"><span className="eyebrow">FleetFlow difference</span><h2>{t('flexibleTitle')}</h2><p>{t('flexibleText')}</p><div className="rate-strip"><div><Clock3/><strong>1–24</strong><span>{t('hour')}</span></div><div><CalendarCheck/><strong>1–30</strong><span>{t('day')}</span></div><div><CalendarCheck/><strong>1–12</strong><span>{t('week')}</span></div><div><CalendarCheck/><strong>1+</strong><span>{t('month')}</span></div></div></div><div className="feature-cards">{[[Search,'smartBooking','smartBookingText'],[ShieldCheck,'trustedFleet','trustedFleetText'],[Percent,'realSavings','realSavingsText']].map(([Icon,title,text]:any)=><article key={title}><span><Icon/></span><h3>{t(title)}</h3><p>{t(text)}</p></article>)}</div></section>
<section className="landing-cta"><div><span className="eyebrow">FleetFlow</span><h2>{t('readyTitle')}</h2><p>{t('readyText')}</p></div><Link href="/register" className="btn light big">{t('getStarted')}<ArrowRight/></Link></section></main>
<footer><Link href="/" className="logo"><span><CarFront/></span>FleetFlow</Link><p>© 2026 FleetFlow. Built for the road ahead.</p><div><a>Privacy</a><a>Terms</a><a>Support</a></div></footer></div>}
