'use client';
import { AlertTriangle, CheckCircle2, X } from 'lucide-react';
import { createContext, useContext, useEffect, useId, useRef, useState } from 'react';
import { useI18n } from '@/lib/i18n';

export function StatusBadge({status}:{status:string}){const{t}=useI18n();return <span className={`status status-${status}`}><i/>{t(status)}</span>}
export function Avatar({name='',initials,size='md'}:{name?:string;initials?:string|null;size?:'sm'|'md'|'lg'}){const value=initials||(name.match(/\b\w/g)||[]).slice(0,2).join('').toUpperCase();return <span className={`avatar avatar-${size}`}>{value}</span>}
export function Skeleton({cards=0,rows=0}:{cards?:number;rows?:number}){return <div className={cards?'skeleton-grid':'skeleton-list'}>{Array.from({length:cards||rows||3}).map((_,i)=><div className={cards?'skeleton-card':'skeleton-row'} key={i}><i/><i/><i/></div>)}</div>}
export function Empty({icon:Icon,title,text,action,label}:{icon:any;title:string;text:string;action?:()=>void;label?:string}){return <div className="empty"><span><Icon size={23}/></span><h3>{title}</h3><p>{text}</p>{action&&<button className="btn primary" onClick={action}>{label}</button>}</div>}
export function Modal({open,onClose,beforeClose,title,subtitle,children,wide=false}:{open:boolean;onClose:()=>void;beforeClose?:()=>boolean|void;title:string;subtitle?:string|React.ReactNode;children:React.ReactNode;wide?:boolean}){const{t}=useI18n();const titleId=useId();const dialogRef=useRef<HTMLDivElement|null>(null);const requestClose=()=>{if(beforeClose&&beforeClose()===false)return;onClose()};useEffect(()=>{const fn=(e:KeyboardEvent)=>e.key==='Escape'&&requestClose();if(open)document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)},[open]);useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;requestAnimationFrame(()=>dialogRef.current?.focus());return()=>previous?.focus?.()},[open]);if(!open)return null;const trapTab=(e:React.KeyboardEvent)=>{if(e.key!=='Tab'||!dialogRef.current)return;const focusables=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'));if(!focusables.length)return;const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&requestClose()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby={titleId} tabIndex={-1} onKeyDown={trapTab} className={`modal ${wide?'wide':''}`}><header><div><h2 id={titleId}>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-btn" onClick={requestClose} aria-label={t('close')}><X size={19}/></button></header><div className="modal-content">{children}</div></div></div>}
type Toast={id:number;message:string;error?:boolean};const Ctx=createContext<(message:string,error?:boolean)=>void>(()=>{});
export function ToastProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<Toast[]>([]);const toast=(message:string,error=false)=>{const id=Date.now()+Math.random();setItems(x=>[...x,{id,message,error}]);setTimeout(()=>setItems(x=>x.filter(y=>y.id!==id)),3500)};return <Ctx.Provider value={toast}>{children}<div className="toasts" role="status" aria-live="polite">{items.map(x=><div className={x.error?'error':''} key={x.id} {...(x.error?{role:'alert'}:{})}>{x.error?<AlertTriangle/>:<CheckCircle2/>}<span>{x.message}</span><button onClick={()=>setItems(v=>v.filter(y=>y.id!==x.id))} aria-label="Dismiss"><X/></button></div>)}</div></Ctx.Provider>}
export const useToast=()=>useContext(Ctx);
