'use client';
import { PackageCheck, Plus, Save } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/client-api';
import { useI18n } from '@/lib/i18n';
import { Modal, Skeleton, useToast } from '@/components/ui';

const blankPlan={code:'',name:'',description:'',monthlyPriceUsd:0,maxVehicles:1,maxRentalRequests:1,storageGb:1,features:[],active:true};
export default function SubscriptionPackagesPage(){
  const{t}=useI18n();const toast=useToast();const[plans,setPlans]=useState<any[]|null>(null);const[saving,setSaving]=useState<number|'add'|null>(null);const[addOpen,setAddOpen]=useState(false);const[addForm,setAddForm]=useState<any>(blankPlan);
  useEffect(()=>{api('/admin/subscription-plans').then((data:any)=>setPlans(data.plans)).catch((error:any)=>toast(error.message,true))},[]);
  const update=(id:number,changes:any)=>setPlans(current=>current?.map(item=>item.id===id?{...item,...changes}:item)||current);
  const save=async(plan:any)=>{setSaving(plan.id);try{const result:any=await api('/admin/subscription-plans',{method:'PATCH',body:JSON.stringify(plan)});update(plan.id,result.plan);toast(t('packageSaved'))}catch(error:any){toast(error.message,true)}finally{setSaving(null)}};
  const openAdd=()=>{setAddForm({...blankPlan,features:[]});setAddOpen(true)};
  const addPlan=async(event:FormEvent)=>{event.preventDefault();setSaving('add');try{const result:any=await api('/admin/subscription-plans',{method:'POST',body:JSON.stringify(addForm)});setPlans(current=>current?[...current,result.plan].sort((a,b)=>a.monthlyPriceUsd-b.monthlyPriceUsd):[result.plan]);setAddOpen(false);toast(t('packageAdded'))}catch(error:any){toast(error.message,true)}finally{setSaving(null)}};
  if(!plans)return <><Skeleton cards={3}/><Skeleton rows={3}/></>;
  return <div className="platform-admin-page admin-tab-page"><section className="admin-section subscription-management-section"><header><div><span><PackageCheck/></span><div><h3>{t('subscriptionPackages')}</h3><p>{t('subscriptionPackagesAdminText')}</p></div></div><button className="btn primary" type="button" onClick={openAdd}><Plus/>{t('addSubscriptionPackage')}</button></header><div className="admin-plan-grid">{plans.map(plan=><article key={plan.id}><div className="admin-plan-heading"><span>{plan.code}</span><label><input type="checkbox" checked={plan.active} onChange={event=>update(plan.id,{active:event.target.checked})}/>{t('active')}</label></div><label>{t('packageName')}<input value={plan.name} onChange={event=>update(plan.id,{name:event.target.value})}/></label><label>{t('description')}<textarea value={plan.description} onChange={event=>update(plan.id,{description:event.target.value})}/></label><div className="admin-limit-grid"><label>{t('monthlyFeeUsd')}<input type="number" min="0" value={plan.monthlyPriceUsd} onChange={event=>update(plan.id,{monthlyPriceUsd:Number(event.target.value)})}/></label><label>{t('vehicleLimit')}<input type="number" min="1" value={plan.maxVehicles} onChange={event=>update(plan.id,{maxVehicles:Number(event.target.value)})}/></label><label>{t('requestLimit')}<input type="number" min="1" value={plan.maxRentalRequests} onChange={event=>update(plan.id,{maxRentalRequests:Number(event.target.value)})}/></label><label>{t('storageGb')}<input type="number" min="1" value={plan.storageGb} onChange={event=>update(plan.id,{storageGb:Number(event.target.value)})}/></label></div><button className="btn secondary" onClick={()=>save(plan)} disabled={saving===plan.id}><Save/>{saving===plan.id?t('saving'):t('savePackage')}</button></article>)}</div></section>
    <Modal open={addOpen} onClose={()=>setAddOpen(false)} title={t('addSubscriptionPackage')} subtitle={t('addSubscriptionPackageText')}><form className="subscription-add-form" onSubmit={addPlan}><div className="subscription-add-grid"><label>{t('packageCode')}<input dir="ltr" autoFocus value={addForm.code} onChange={event=>setAddForm({...addForm,code:event.target.value.toUpperCase()})} placeholder={t('packageCodePlaceholder')} maxLength={32} required/><small>{t('packageCodeHint')}</small></label><label>{t('packageName')}<input value={addForm.name} onChange={event=>setAddForm({...addForm,name:event.target.value})} required/></label><label className="span-2">{t('description')}<textarea value={addForm.description} onChange={event=>setAddForm({...addForm,description:event.target.value})} required/></label></div><div className="subscription-add-limits"><label>{t('monthlyFeeUsd')}<input type="number" min="0" step="0.01" value={addForm.monthlyPriceUsd} onChange={event=>setAddForm({...addForm,monthlyPriceUsd:Number(event.target.value)})} required/></label><label>{t('vehicleLimit')}<input type="number" min="1" step="1" value={addForm.maxVehicles} onChange={event=>setAddForm({...addForm,maxVehicles:Number(event.target.value)})} required/></label><label>{t('requestLimit')}<input type="number" min="1" step="1" value={addForm.maxRentalRequests} onChange={event=>setAddForm({...addForm,maxRentalRequests:Number(event.target.value)})} required/></label><label>{t('storageGb')}<input type="number" min="1" step="1" value={addForm.storageGb} onChange={event=>setAddForm({...addForm,storageGb:Number(event.target.value)})} required/></label></div><label className="subscription-add-active"><input type="checkbox" checked={addForm.active} onChange={event=>setAddForm({...addForm,active:event.target.checked})}/><span><strong>{t('activatePackage')}</strong><small>{t('activatePackageText')}</small></span></label><footer><button type="button" className="btn secondary" onClick={()=>setAddOpen(false)}>{t('cancel')}</button><button className="btn primary" disabled={saving==='add'}><Plus/>{saving==='add'?t('saving'):t('addSubscriptionPackage')}</button></footer></form></Modal>
  </div>;
}
