import { and, desc, eq, ilike, or, sql } from 'drizzle-orm';
import { getDb } from '@/db';
import { companies, promotionVehicles, promotions, vehicles } from '@/db/schema';
import { requireUser } from '@/lib/auth';
import { fail, ok } from '@/lib/http';
import { promotionState } from '@/lib/pricing';

export async function GET(request:Request){try{const user=await requireUser();const db=await getDb();const url=new URL(request.url);const search=url.searchParams.get('search');const conditions:any[]=[];if(user.role==='company')conditions.push(eq(vehicles.companyId,user.companyId!));else conditions.push(eq(vehicles.status,'available'));if(search)conditions.push(or(ilike(vehicles.make,`%${search}%`),ilike(vehicles.model,`%${search}%`),ilike(vehicles.trim,`%${search}%`),ilike(vehicles.licensePlate,`%${search}%`)));const rows=await db.select({id:vehicles.id,companyId:vehicles.companyId,companyName:companies.name,make:vehicles.make,model:vehicles.model,trim:vehicles.trim,year:vehicles.year,category:vehicles.category,bodyType:vehicles.bodyType,gearbox:vehicles.gearbox,drivetrain:vehicles.drivetrain,steeringType:vehicles.steeringType,fuel:vehicles.fuel,seats:vehicles.seats,color:vehicles.color,licensePlate:vehicles.licensePlate,odometer:vehicles.odometer,location:vehicles.location,features:vehicles.features,image:vehicles.image,status:vehicles.status,hourlyRate:vehicles.hourlyRate,dailyRate:vehicles.dailyRate,weeklyRate:vehicles.weeklyRate,monthlyRate:vehicles.monthlyRate,rating:vehicles.rating,createdAt:vehicles.createdAt}).from(vehicles).innerJoin(companies,eq(vehicles.companyId,companies.id)).where(and(...conditions)).orderBy(desc(vehicles.createdAt));const companyIds=[...new Set(rows.map((v:any)=>v.companyId))];const promoRows=companyIds.length?await db.select().from(promotions):[];const links=companyIds.length?await db.select().from(promotionVehicles):[];const result=rows.map((v:any)=>({...v,promotions:promoRows.filter((p:any)=>p.companyId===v.companyId&&promotionState(p)==='live'&&(p.appliesTo==='all'||links.some((x:any)=>x.promotionId===p.id&&x.vehicleId===v.id))).map((p:any)=>({...p,state:promotionState(p)}))}));return ok({vehicles:result})}catch(error){return fail(error)}}

export async function POST(request:Request){try{const user=await requireUser('company');const body=await request.json();const required=['make','model','year','category','color','licensePlate','location','hourlyRate','dailyRate','weeklyRate','monthlyRate'];for(const field of required)if(body[field]===undefined||body[field]==='')throw new Error(`Missing ${field}`);const db=await getDb();const[row]=await db.insert(vehicles).values({companyId:user.companyId!,make:body.make,model:body.model,trim:body.trim||'Standard',year:Number(body.year),category:body.category,bodyType:body.bodyType||'Sedan',gearbox:body.gearbox||'Automatic',drivetrain:body.drivetrain||'FWD',steeringType:body.steeringType||'Left-hand drive',fuel:body.fuel||'Petrol',seats:Number(body.seats||5),color:body.color,licensePlate:body.licensePlate.toUpperCase(),odometer:Number(body.odometer||0),location:body.location,features:body.features||[],image:body.image||'/cars/audi.jpg',status:body.status||'available',hourlyRate:Number(body.hourlyRate),dailyRate:Number(body.dailyRate),weeklyRate:Number(body.weeklyRate),monthlyRate:Number(body.monthlyRate),rating:5}).returning();return ok({vehicle:row},201)}catch(error){return fail(error)}}
