'use client';
import { Building2, CheckCircle2, ExternalLink, FileText, ShieldCheck, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api, apiFile } from '@/lib/client-api';
import { money } from '@/lib/format';
import { useI18n } from '@/lib/i18n';
import { Skeleton, useToast } from '@/components/ui';

export default function VerificationRequestsPage(){
  const{t}=useI18n();const toast=useToast();const[data,setData]=useState<any>(null);const[notes,setNotes]=useState<Record<number,string>>({});const[saving,setSaving]=useState<number|null>(null);const[filter,setFilter]=useState('pending');
  const load=()=>api('/admin/verifications').then(setData).catch((error:any)=>toast(error.message,true));useEffect(()=>{load()},[]);
  const requests=useMemo(()=>data?.requests?.filter((item:any)=>filter==='all'||item.status===filter)||[],[data,filter]);
  const review=async(id:number,action:'approve'|'reject')=>{setSaving(id);try{await api('/admin/verifications',{method:'PATCH',body:JSON.stringify({id,action,reviewNotes:notes[id]||''})});toast(t(action==='approve'?'companyApproved':'companyRejected'));await load()}catch(error:any){toast(error.message,true)}finally{setSaving(null)}};
  const openDocument=async(id:number,type:string)=>{try{const blob=await apiFile(`/company-verification/${id}/document/${type}`);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60_000)}catch(error:any){toast(error.message,true)}};
  if(!data)return <><Skeleton cards={3}/><Skeleton rows={6}/></>;
  return <div className="platform-admin-page admin-tab-page">
    <div className="metrics admin-metrics">{[[t('registeredCompanies'),data.stats.companies,Building2,'green'],[t('pendingVerification'),data.stats.pending,FileText,'amber'],[t('verifiedCompanies'),data.stats.verified,CheckCircle2,'blue']].map(([label,value,Icon,tone]:any)=><article className="metric" key={label}><div className={`metric-icon ${tone}`}><Icon/></div><span>{label}</span><strong>{value}</strong></article>)}</div>
    <section className="panel admin-verifications"><header><div><h3>{t('verificationQueue')}</h3><p>{t('verificationQueueText')}</p></div><div className="admin-filter-tabs">{['pending','approved','rejected','all'].map(value=><button className={filter===value?'active':''} onClick={()=>setFilter(value)} key={value}>{t(value==='all'?'All':`verification_${value}`)}</button>)}</div></header>{requests.length?<div className="admin-request-list">{requests.map((request:any)=><article key={request.id}><div className="admin-request-company"><span>{request.companyName.split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</span><div><h3>{request.companyName}</h3><p>{request.submitterName} · {request.submitterEmail}</p><small>{request.companyCity} · {t('attempt')} {request.attempt} · {new Date(request.createdAt).toLocaleString()}</small></div><em className={`verification-pill ${request.status}`}>{t(`verification_${request.status}`)}</em></div><div className="admin-request-details"><span><small>{t('subscriptionPackage')}</small><strong>{request.planName}</strong></span><span><small>{t('monthlyFee')}</small><strong>{money(request.monthlyPriceUsd)}</strong></span><span><small>{t('paymentReference')}</small><strong dir="ltr">{request.subscriptionPaymentCode}</strong></span><span><small>{t('packageLimits')}</small><strong>{request.maxVehicles} / {request.maxRentalRequests.toLocaleString()} / {request.storageGb} GB</strong></span></div><div className="admin-document-actions"><button onClick={()=>openDocument(request.id,'business')}><FileText/>{t('businessRegistration')}<ExternalLink/></button><button onClick={()=>openDocument(request.id,'tax')}><FileText/>{t('taxCertificate')}<ExternalLink/></button><button onClick={()=>openDocument(request.id,'owner')}><FileText/>{t('ownerIdentity')}<ExternalLink/></button></div>{request.status==='pending'?<><label className="review-notes">{t('reviewNotes')}<textarea value={notes[request.id]||''} onChange={event=>setNotes(current=>({...current,[request.id]:event.target.value}))} placeholder={t('reviewNotesPlaceholder')}/></label><footer><button className="btn secondary danger" disabled={saving===request.id} onClick={()=>review(request.id,'reject')}><XCircle/>{t('reject')}</button><button className="btn primary" disabled={saving===request.id} onClick={()=>review(request.id,'approve')}><CheckCircle2/>{t('approveCompany')}</button></footer></>:request.reviewNotes&&<div className="admin-review-result"><ShieldCheck/><span><strong>{t('reviewNotes')}</strong><p>{request.reviewNotes}</p></span></div>}</article>)}</div>:<div className="admin-empty"><CheckCircle2/><strong>{t('verificationQueueEmpty')}</strong><p>{t('verificationQueueEmptyText')}</p></div>}</section>
  </div>;
}
