'use client';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, Check, Fuel, Gauge, MapPin, ShieldCheck, Star, UserRound, Zap } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { BookingModal } from '@/components/booking-modal';
import { Skeleton, StatusBadge } from '@/components/ui';
import { api } from '@/lib/client-api';
import { dateTime, money } from '@/lib/format';
import { useI18n } from '@/lib/i18n';

export default function BrowseDetail(){const{t}=useI18n();const{id}=useParams();const[data,setData]=useState<any>(null);const[booking,setBooking]=useState(false);useEffect(()=>{api(`/vehicles/${id}`).then(setData)},[id]);if(!data)return <Skeleton rows={6}/>;const v=data.vehicle;return <><Link className="back-link" href="/dashboard/browse"><ArrowLeft/>{t('browse')}</Link><div className="market-detail"><section><div className="detail-photo"><img src={v.image}/><StatusBadge status={v.status}/><span className="rating-badge"><Star fill="currentColor"/>{v.rating}</span></div><div className="market-detail-title"><div><span>{v.companyName}</span><h2>{v.make} {v.model}</h2><p>{v.year} · {t(v.category)}</p></div><div><small>{t('from')}</small><strong>{money(v.dailyRate)}</strong><span>/{t('day')}</span></div></div><div className="detail-icon-specs">{[[Gauge,t(v.gearbox)],[Fuel,t(v.fuel)],[UserRound,`${v.seats} ${t('seats')}`],[MapPin,v.location]].map(([Icon,value]:any)=><div key={value}><Icon/><span>{value}</span></div>)}</div><section className="panel included"><h3>{t('everythingNeed')}</h3><div>{v.features.map((x:string)=><span key={x}><Check/>{t(x)}</span>)}</div></section></section><aside><section className="panel booking-card"><h3>{t('pricing')}</h3>{[['hour',v.hourlyRate],['day',v.dailyRate],['week',v.weeklyRate],['month',v.monthlyRate]].map(([label,value])=><div key={label}><span>{t('per')} {t(label as string)}</span><strong>{money(value as number)}</strong></div>)}<button className="btn primary" onClick={()=>setBooking(true)}>{t('rentNow')}</button><p><ShieldCheck/>{t('protectedBooking')}</p></section>{data.promotions.length>0&&<section className="panel available-deals"><h3><Zap/>{t('deals')}</h3>{data.promotions.map((p:any)=><div key={p.id}><span><strong>{p.name}</strong><small>{t('use')} {p.code}</small></span><em>{p.type==='percentage'?`${p.value}% ${t('off')}`:`${money(p.value)} ${t('off')}`}</em></div>)}</section>}<section className="panel busy-card"><h3><CalendarDays/>{t('busyPeriods')}</h3>{data.busyPeriods.length?data.busyPeriods.map((p:any,i:number)=><p key={i}>{dateTime(p.startsAt)}<br/>→ {dateTime(p.endsAt)}<br/><small>{t('turnaroundUntil')} {dateTime(p.blockedUntil)}</small></p>):<p>{t('noUpcomingBookings')}</p>}</section></aside></div>{booking&&<BookingModal vehicle={v} onClose={()=>setBooking(false)}/>}</>}
