'use client';
import { Building2, CheckCircle2, Clock3, CreditCard, FileCheck2, ShieldCheck, Upload, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/client-api';
import { money } from '@/lib/format';
import { useI18n } from '@/lib/i18n';
import { Skeleton, useToast } from '@/components/ui';

type UploadValue={name:string;mime:string;data:string};
const readUpload=(file:File)=>new Promise<UploadValue>((resolve,reject)=>{
  if(file.size>5*1024*1024)return reject(new Error('Each document must be no larger than 5 MB.'));
  const reader=new FileReader();reader.onerror=()=>reject(new Error('Unable to read the document.'));
  reader.onload=()=>resolve({name:file.name,mime:file.type,data:String(reader.result).split(',')[1]||''});reader.readAsDataURL(file);
});
export default function CompanyVerificationPage(){
  const{t}=useI18n();const toast=useToast();const[data,setData]=useState<any>(null);const[planCode,setPlanCode]=useState('STARTER');
  const[paymentCode,setPaymentCode]=useState('');const[documents,setDocuments]=useState<Record<string,UploadValue>>({});const[submitting,setSubmitting]=useState(false);const[paying,setPaying]=useState(false);
  const load=()=>api('/company-verification').then((value:any)=>{setData(value);if(value.latestRequest?.planCode)setPlanCode(value.latestRequest.planCode);window.dispatchEvent(new Event('fleetflow:profile:refresh'))}).catch((e:any)=>toast(e.message,true));
  useEffect(()=>{load()},[]);
  const selected=useMemo(()=>data?.plans?.find((plan:any)=>plan.code===planCode),[data,planCode]);
  const setDocument=async(key:string,file?:File)=>{if(!file)return;try{const value=await readUpload(file);setDocuments(current=>({...current,[key]:value}))}catch(error:any){toast(error.message,true)}};
  const submit=async()=>{setSubmitting(true);try{await api('/company-verification',{method:'POST',body:JSON.stringify({planCode,subscriptionPaymentCode:paymentCode,businessRegistration:documents.business,taxCertificate:documents.tax,ownerIdentity:documents.owner})});toast(t('verificationSubmitted'));setDocuments({});await load()}catch(error:any){toast(error.message,true)}finally{setSubmitting(false)}};
  const autoPay=async()=>{setPaying(true);try{const result:any=await api('/payments/kuraimi',{method:'POST',body:JSON.stringify({planCode})});setPaymentCode(result.payment.providerReference||result.payment.internalReference);if(result.payment.checkoutUrl)window.open(result.payment.checkoutUrl,'_blank','noopener,noreferrer');toast(t('paymentRequestCreated'))}catch(error:any){toast(error.message,true)}finally{setPaying(false)}};
  if(!data)return <><div className="page-heading"><div><h2>{t('companyVerification')}</h2><p>{t('loading')}</p></div></div><Skeleton cards={3}/><Skeleton rows={4}/></>;
  const status=data.company.verificationStatus;const canApply=status==='unsubmitted'||status==='rejected';const latest=data.latestRequest;
  return <div className="verification-page">
    <div className="page-heading"><div><span className="eyebrow"><ShieldCheck/>{t('trustedMarketplace')}</span><h2>{t('companyVerification')}</h2><p>{t('companyVerificationText')}</p></div></div>
    <section className={`verification-status-card status-${status}`}><span>{status==='verified'?<CheckCircle2/>:status==='rejected'?<XCircle/>:<Clock3/>}</span><div><small>{t('verificationStatus')}</small><h3>{t(`verification_${status}`)}</h3><p>{status==='verified'?t('verificationVerifiedText'):status==='pending'?t('verificationPendingText'):status==='rejected'?(latest?.reviewNotes||t('verificationRejectedText')):t('verificationUnsubmittedText')}</p></div>{latest&&<em>#{latest.id} · {t('attempt')} {latest.attempt}</em>}</section>
    {status==='verified'&&data.entitlement.plan&&<><section className="panel subscription-summary"><header><div><h3>{t('activeSubscription')}</h3><p>{data.entitlement.plan.description}</p></div><strong>{data.entitlement.plan.name}</strong></header><div><span>{t('vehiclesUsed')}<strong>{data.entitlement.usage.vehicles} / {data.entitlement.effectiveLimits.maxVehicles}</strong></span><span>{t('requestsThisMonth')}<strong>{data.entitlement.usage.rentalRequestsThisMonth} / {data.entitlement.effectiveLimits.maxRentalRequests}</strong></span><span>{t('storageAllowance')}<strong>{data.entitlement.effectiveLimits.storageGb} GB</strong></span></div></section></>}
    {canApply&&<>
      {status==='rejected'&&<div className="verification-retry"><XCircle/><div><strong>{t('requestRejected')}</strong><p>{latest?.reviewNotes}</p><small>{t('retryVerificationHint')}</small></div></div>}
      <section className="verification-section"><header><span>01</span><div><h3>{t('chooseSubscription')}</h3><p>{t('chooseSubscriptionText')}</p></div></header><div className="subscription-plan-grid">{data.plans.map((plan:any)=><button type="button" className={planCode===plan.code?'active':''} onClick={()=>setPlanCode(plan.code)} key={plan.id}><small>{plan.code}</small><h3>{plan.name}</h3><strong>{money(plan.monthlyPriceUsd)}<em>/{t('month')}</em></strong><p>{plan.description}</p><ul><li>{plan.maxVehicles} {t('vehicles')}</li><li>{plan.maxRentalRequests.toLocaleString()} {t('requestsPerMonth')}</li><li>{plan.storageGb} GB {t('storage')}</li></ul>{planCode===plan.code&&<CheckCircle2/>}</button>)}</div></section>
      <section className="verification-section"><header><span>02</span><div><h3>{t('subscriptionPayment')}</h3><p>{t('subscriptionPaymentText')}</p></div></header><div className="bank-account-grid">{data.banks.length?data.banks.map((bank:any)=><article key={bank.id}><CreditCard/><div><small>{bank.label}</small><strong dir="ltr">{bank.accountNumber}</strong><span>{bank.accountHolder} · {bank.currency}</span>{bank.instructions&&<p>{bank.instructions}</p>}</div></article>):<p className="empty-inline">{t('bankAccountsComingSoon')}</p>}</div><div className="payment-code-row"><label>{t('subscriptionPaymentCode')}<input value={paymentCode} onChange={event=>setPaymentCode(event.target.value)} placeholder="TRX-123456" required/><small>{t('subscriptionPaymentCodeHint')}</small></label>{data.kuraimiPayment.enabled&&data.kuraimiPayment.configured&&<button type="button" className="btn secondary" onClick={autoPay} disabled={paying||!selected}><CreditCard/>{paying?t('loading'):t('payAutomaticallyKuraimi')}</button>}</div></section>
      <section className="verification-section"><header><span>03</span><div><h3>{t('verificationDocuments')}</h3><p>{t('verificationDocumentsText')}</p></div></header><div className="verification-upload-grid">{[['business','businessRegistration'],['tax','taxCertificate'],['owner','ownerIdentity']].map(([key,label])=><label className={documents[key]?'ready':''} key={key}><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={event=>setDocument(key,event.target.files?.[0])}/>{documents[key]?<FileCheck2/>:<Upload/>}<strong>{t(label)}</strong><span>{documents[key]?.name||t('uploadDocument')}</span><small>PDF, JPG, PNG, WebP · 5 MB</small></label>)}</div><button className="btn primary verification-submit" onClick={submit} disabled={submitting||!selected||paymentCode.trim().length<4||!documents.business||!documents.tax||!documents.owner}><ShieldCheck/>{submitting?t('submitting'):t('submitVerification')}</button></section>
    </>}
    {latest&&<section className="panel verification-history"><header><div><h3>{t('latestVerificationRequest')}</h3><p>{new Date(latest.createdAt).toLocaleString()}</p></div><span className={`verification-pill ${latest.status}`}>{t(`verification_${latest.status}`)}</span></header><div><span><Building2/><small>{t('subscriptionPackage')}</small><strong>{latest.planName}</strong></span><span><CreditCard/><small>{t('paymentReference')}</small><strong dir="ltr">{latest.subscriptionPaymentCode}</strong></span><span><FileCheck2/><small>{t('documents')}</small><strong>3</strong></span></div>{latest.reviewNotes&&<p>{latest.reviewNotes}</p>}</section>}
  </div>;
}
